import React, { createContext, useContext, useState, useEffect, ReactNode, useMemo } from "react";
import { EducationalStage, useStage } from "./StageContext";

export interface Guardian {
  id: string;
  name: string;
  phone: string;
  relation: string;
  address?: string;
  gender?: "ذكر" | "أنثى";
  isDeleted?: boolean;
  deletedAt?: string;
}

export interface EnrollmentRecord {
  id: string;
  academicYearId: string;
  grade: string;
  status: "ناجح" | "راسب" | "منقول" | "خريج";
  date: string;
}

export interface Student {
  id: string;
  name: string;
  dob: string;
  nationalId: string;
  guardianName: string;
  stage: EducationalStage;
  grade: string;
  
  // New Detailed Info
  gender?: "ذكر" | "أنثى";
  sectionId?: string; // Links to Section
  address?: string;
  guardianPhone?: string;
  guardianRelation?: string;
  bloodType?: string;
  medicalNotes?: string;
  enrollmentDate?: string;
  academicYearId?: string;
  status?: "نشط" | "موقوف" | "منقول" | "خريج" | "راسب" | "ناجح";
  enrollmentHistory?: EnrollmentRecord[];
  major?: "science" | "literature";
  pickupPersons?: string;
  specialCare?: boolean;
  elective?: string;
  isDeleted?: boolean;
  deletedAt?: string;
}

export interface StudentEnrollment {
  id: string;
  studentId: string;
  academicYearId: string;
  stage: EducationalStage;
  grade: string;
  sectionId?: string;
  major?: "science" | "literature";
  elective?: string;
  status: "نشط" | "موقوف" | "منقول" | "خريج" | "راسب" | "ناجح";
  enrollmentDate: string;
}

export interface AcademicYear {
  id: string;
  name: string; // e.g. "١٤٤٥ / ١٤٤٦ هـ"
  startDate: string;
  endDate: string;
  isCurrent: boolean;
}

export interface TeachingAssignment {
  id: string;
  teacherId: string;
  subjectId: string;
  sectionId: string;
  yearId: string;
  stage: EducationalStage;
}

export interface KindergartenStudent extends Student {
  stage: "kindergarten";
  pickupPersons: string;
  allergies: string;
  specialCare: boolean;
}

export interface HighSchoolStudent extends Student {
  stage: "high";
  major: "science" | "literature";
  elective: string;
}

export type EntityType = 'student' | 'staff' | 'guardian' | 'enrollment' | 'invoice' | 'payment' | 'expense' | 'payroll' | 'none';

export interface Invoice {
  id: string;
  studentId: string; // Kept for backward compatibility
  enrollmentId?: string; // New ERP requirement
  academicYearId?: string;
  studentName: string; 
  title?: string;
  amount: number;
  discountId?: string;
  discountAmount?: number;
  netAmount?: number;
  paid: number;
  dueDate: string;
  issueDate?: string;
  status: "draft" | "approved" | "issued" | "partial" | "paid" | "cancelled" | "written_off";
  stage: EducationalStage;
}

export interface FeeStructure {
  id: string;
  name: string;
  amount: number;
  type: string;
  stage: EducationalStage | "all";
  grades?: string[];
  sections?: string[];
  isMandatory: boolean;
}

export interface Discount {
  id: string;
  name: string;
  type: "percentage" | "fixed";
  value: number;
  description?: string;
  isActive?: boolean;
  stage?: EducationalStage | "all";
  grades?: string[];
  sections?: string[];
  studentIds?: string[];
}

export interface Payment {
  id: string;
  invoiceId: string;
  studentId: string;
  enrollmentId?: string;
  academicYearId?: string;
  amount: number;
  date: string;
  method: "cash" | "bank_transfer" | "card" | "cheque";
  referenceNo?: string;
  notes?: string;
}

export interface ExpenseCategory {
  id: string;
  name: string;
}

export interface Expense {
  id: string;
  title: string;
  amount: number;
  date: string;
  categoryId: string;
  beneficiary: string;
  method: "cash" | "bank_transfer" | "card" | "cheque";
  referenceNo?: string;
  notes?: string;
  academicYearId?: string;
  costCenterId?: string;
  status?: "draft" | "submitted" | "reviewed" | "approved" | "paid" | "posted";
}

export interface Account {
  id: string;
  name: string;
  type: "asset" | "liability" | "equity" | "revenue" | "expense";
  code: string;
  description?: string;
  isSystemAccount?: boolean;
  parentId?: string;
  isActive?: boolean;
  isFavorite?: boolean;
  lastUsedDate?: string;
  requiredEntityType?: EntityType;
  costCenterId?: string;
}

export interface JournalEntry {
  id: string;
  academicYearId: string;
  date: string;
  referenceId?: string;
  referenceType?: "invoice" | "payment" | "expense" | "manual" | "payroll";
  description: string;
  status: "posted" | "draft" | "voided";
  isAutoGenerated?: boolean;
  sourceDocumentType?: EntityType;
  sourceDocumentId?: string;
  costCenterId?: string;
  financialPeriodId?: string;
}

export interface JournalLine {
  id: string;
  journalEntryId: string;
  accountId: string;
  debit: number;
  credit: number;
  studentId?: string;
  referenceId?: string;
  referenceType?: EntityType;
  description?: string;
}

export interface AuditLog {
  id: string;
  userId: string;
  userName: string;
  action: "create" | "update" | "delete";
  entityType: EntityType | string;
  entityId: string;
  timestamp: string;
  oldValue?: string;
  newValue?: string;
  details?: string;
}

export interface Book {
  id: string;
  title: string;
  author: string;
  category: string;
  copies: number;
  available: number;
  stage: EducationalStage;
}

export interface LibraryIssue {
  id: string;
  bookId: string;
  bookTitle: string;
  studentId: string;
  studentName: string;
  issueDate: string;
  dueDate: string;
  status: "active" | "returned" | "overdue";
  stage: EducationalStage;
}

export interface InventoryItem {
  id: string;
  name: string;
  category: string;
  quantity: number;
  price: string;
  status: "available" | "low_stock" | "out_of_stock";
}

export interface InventoryTransaction {
  id: string;
  type: "issue" | "receive";
  itemId: string;
  itemName: string;
  quantity: number;
  date: string;
  by: string;
  to: string;
}

export interface Staff {
  id: string;
  name: string;
  role: string;
  department: string;
  status: "active" | "on_leave" | "terminated";
  stage: EducationalStage | "all"; // some staff serve specific stages, some all
  employeeNo?: string;
  phone?: string;
  email?: string;
  subjects?: string[];
  sections?: string[];
  isDeleted?: boolean;
  deletedAt?: string;
  basicSalary?: number;
  allowance?: number;
  deduction?: number;
  // New Payroll Fields
  paymentType?: "Monthly" | "PerLesson" | "Daily";
  rate?: number;
  hireDate?: string;
}

export interface EmployeeAssignment {
  id: string;
  employeeId: string;
  academicYearId: string;
  stage: EducationalStage | "all";
  role: string;
  department: string;
  status: "active" | "on_leave" | "terminated";
  basicSalary?: number;
  allowance?: number;
  deduction?: number;
  paymentType?: "Monthly" | "PerLesson" | "Daily";
  rate?: number;
  subjects?: string[];
  sections?: string[];
}

export interface ClinicVisit {
  id: string;
  studentId: string;
  studentName: string;
  date: string;
  symptoms: string;
  diagnosis: string;
  actionTaken: string;
  stage: EducationalStage;
}

export interface AttendanceSession {
  id: string;
  academicYearId: string;
  sectionId: string;
  subjectId: string;
  teacherId: string;
  periodNumber: number;
  date: string;
  status: "open" | "closed";
  createdBy: string;
  createdAt: string;
}

export interface AttendanceRecord {
  id: string;
  sessionId: string;
  studentEnrollmentId: string;
  status: "PRESENT" | "ABSENT" | "LATE" | "EXCUSED" | "LEFT_EARLY" | "SICK" | "SUSPENDED" | "REMOTE";
  reason?: string;
  note?: string;
  markedBy: string;
  markedAt: string;
}

export interface AttendanceExcuse {
  id: string;
  studentEnrollmentId: string;
  attendanceRecordId: string;
  reason: string;
  attachment?: string;
  status: "Pending" | "Approved" | "Rejected";
  approvedBy?: string;
  approvedAt?: string;
}

export interface BehaviorTransaction {
  id: string;
  studentEnrollmentId: string;
  type: "positive" | "negative";
  points: number;
  categoryId?: string;
  reason: string;
  createdBy: string;
  date: string;
}

export interface DisciplineCategory {
  id: string;
  name: string;
  type: "academic" | "behavioral" | "appearance";
  severity: "low" | "medium" | "high";
  defaultPoints: number;
  recommendedAction: string;
}

export interface DisciplineIncident {
  id: string;
  studentEnrollmentId: string;
  date: string;
  location?: string;
  description: string;
  witnesses?: string;
  responsiblePerson: string;
  attachments?: string;
  actionTaken?: string;
}

export interface DisciplineAction {
  id: string;
  incidentId: string;
  type: string;
  date: string;
  responsiblePerson: string;
  notes?: string;
}

export interface Section {
  id: string;
  name: string;
  grade: string;
  capacity: number;
  stage: EducationalStage;
  homeroomTeacher?: string;
}

export interface ScheduleSlot {
  id: string;
  sectionId: string;
  day: string;
  period: number;
  subjectId: string;
  teacherId: string;
  stage: EducationalStage;
}

export interface Exam {
  id: string;
  academicYearId: string;
  name: string; // e.g., "اختبار منتصف الفصل الدراسي الأول"
  term: string; // "الفصل الأول"
  type: "midterm" | "final" | "quiz" | "monthly";
  startDate: string;
  endDate: string;
  status: "draft" | "upcoming" | "ongoing" | "grading" | "completed";
}

export interface ExamSubject {
  id: string;
  examId: string;
  subjectId: string;
  date: string; // specific date for this subject's exam
  maxScore: number;
  passScore: number;
  weight: number; // e.g., 20% of the term
  stage: EducationalStage | "all";
  grade: string; // e.g. "الصف الأول"
}

export interface ExamResult {
  id: string;
  examSubjectId: string;
  studentEnrollmentId: string;
  mark: number;
  notes?: string;
  status: "draft" | "submitted" | "approved" | "published";
}

export interface Subject {
  id: string;
  name: string;
  code: string;
  creditHours: number;
  stage: EducationalStage | "all";
  grades?: string[]; // Array of grades this subject is taught in
  fee?: number; // Optional fee associated with the subject (e.g. lab fee)
}

export interface MaintenanceRequest {
  id: string;
  title: string;
  description: string;
  location: string;
  priority: "high" | "medium" | "low";
  status: "new" | "in_progress" | "completed";
  costEstimate?: number;
  dateRequested: string;
  dateCompleted?: string;
}

export interface Room {
  id: string;
  name: string;
  building: string;
  floor: string;
  type: "classroom" | "lab" | "office" | "hall";
  capacity: number;
  status: "available" | "occupied" | "maintenance";
}

export interface StaffEvaluation {
  id: string;
  staffId: string;
  staffName: string;
  period: string;
  evaluator: string;
  date: string;
  criteria: {
    commitment: number;
    performance: number;
    cooperation: number;
    creativity: number;
  };
  overallScore: number;
  notes?: string;
}

export interface StaffContract {
  id: string;
  staffId: string;
  staffName: string;
  type: "full_time" | "part_time" | "contractor";
  startDate: string;
  endDate: string;
  basicSalary: number;
  status: "active" | "expired" | "renewing";
}

export interface StaffLeave {
  id: string;
  staffId: string;
  staffName: string;
  type: "annual" | "sick" | "issued" | "emergency";
  startDate: string;
  endDate: string;
  days: number;
  status: "pending" | "approved" | "rejected";
  notes?: string;
}

export interface StaffAttendanceRecord {
  id?: string;
  staffId: string;
  date: string;
  status: "present" | "late" | "absent" | "excused";
  checkIn?: string;
  checkOut?: string;
  minutesLate?: number;
  deductionAmount?: number;
  notes?: string;
}

export interface StaffAdvance {
  id: string;
  staffId: string;
  staffName: string;
  amount: number;
  date: string;
  status: "pending" | "approved" | "rejected" | "paid";
  notes?: string;
  deductFromPayrollDate?: string;
  deductionMonth?: string;
}

export interface ActivityLog {
  id: string;
  user: string;
  action: string;
  entity: string;
  details: string;
  date: string;
  ip?: string;
}

export interface Textbook {
  id: string;
  title: string;
  subject: string;
  gradeId: string;
  term?: string;
  copies: number;
  stage: string;
}

export interface TextbookDistribution {
  id: string;
  textbookId: string;
  studentId: string;
  date: string;
  status: string;
  stage: string;
}

export interface TransportRoute {
  id: string;
  name: string;
  destination: string;
  driverName: string;
  driverPhone: string;
  supervisorName: string;
  vehiclePlate: string;
  capacity: number;
  stops: number;
  feeAmount: number;
  feeMode: "annual" | "term" | "monthly";
}

export interface TransportSubscription {
  id: string;
  studentId: string;
  routeId: string;
  direction: string;
  status: string;
  fee?: number;
}

export interface TimetableSettings {
  maxPeriodsPerDay: number;
  breakDuration: number;
  periodDuration: number;
  stage: string;
}

export interface AppNotification {
  id: string;
  title: string;
  message: string;
  type: "info" | "success" | "warning" | "danger";
  timestamp: string;
  read: boolean;
  actionUrl?: string;
}

export interface SystemSettings {
  schoolName: string;
  licenseNumber: string;
  phone: string;
  email: string;
  address: string;
  principalName: string;
  vision: string;
  roomCategories: string;
  assetCategories: string;
  roomNumbering: string;
  maintenanceAlert: string;
  inventoryAlertLimit: number;
  inventoryMethod: string;
  winterTime: string;
  summerTime: string;
  lateAsPartialAbsence: boolean;
  deductBehaviorOnAbsence: boolean;
  taxNumber: string;
  vatRate: number;
  refundPolicy: string;
  autoTransferPayroll: boolean;
  autoMaintenanceExpense: boolean;
  autoLibraryFee: boolean;
  annualLeaveDays: number;
  lateDeductionRate: number;
  gracePeriod: boolean;
  fingerprintSync: boolean;
  admissionStatus: string;
  maxClassSize: number;
  reqBirthCert: boolean;
  reqVaccine: boolean;
  reqPrevCert: boolean;
  reqFamilyCard: boolean;
  whatsappApiToken?: string;
  smsProvider?: string;
  googleWorkspace?: boolean;
  microsoftTeams?: boolean;
  moodleIntegration?: boolean;
  zoomIntegration?: boolean;
  paymentGateway?: string;
  stripePubKey?: string;
  stripeSecretKey?: string;
  paytabsProfileId?: string;
  paytabsServerKey?: string;
  footerText: string;
  defaultTemplate: string;
  rowsPerBatch: string;
  qrCodeUsage: string;
  headerEntity: string;
  headerDepartment: string;
  qrVerifyUrl: string;
  qrExpiry: string;
  qrIncludeId: boolean;
  themeMode: "light" | "dark" | "system";
  primaryColor: string;
  language: "ar" | "en";
  dateFormat: string;
  defaultChannels: { email: boolean; sms: boolean; push: boolean };
  mobileLoginPolicy: string;
  notifSync: string;
  parentViewLimit: boolean;
  teacherViewLimit: boolean;
  hideFinancial: boolean;
  logMobileActivity: boolean;
  apiKey: string;
  webhookUrl: string;
  whStudentCreated: boolean;
  whInvoicePaid: boolean;
  whExamUpdated: boolean;
  whTransportChanged: boolean;
  apiRateLimit: number;
  apiAccessScope: string;
  apiAllowedIps: string;
  passwordPolicy: string;
  sessionTimeout: string;
  force2FA: boolean;
  lockAfter5Fails: boolean;
}

export const defaultSettings: SystemSettings = {
  schoolName: "مدرسة النموذج الأهلية",
  licenseNumber: "LIC-2024-001",
  phone: "0112345678",
  email: "info@school.edu",
  address: "الرياض - حي الواحة",
  principalName: "خالد القحطاني",
  vision: "الريادة في التعليم وصناعة جيل واعٍ مبتكر",
  roomCategories: "فصل دراسي,معمل,مكتبة,صالة رياضية,مسرح,قاعة اجتماعات",
  assetCategories: "أثاث مدرسي,أجهزة إلكترونية,معدات رياضية,كتب ومراجع,أخرى",
  roomNumbering: "ترقيم تلقائي (RM-XXXX)",
  maintenanceAlert: "مفعل (قبل 7 أيام)",
  inventoryAlertLimit: 10,
  inventoryMethod: "FIFO (ما يدخل أولاً يخرج أولاً)",
  winterTime: "07:30",
  summerTime: "06:45",
  lateAsPartialAbsence: true,
  deductBehaviorOnAbsence: true,
  taxNumber: "300012345600003",
  vatRate: 15,
  refundPolicy: "خلال 14 يوم من التسجيل",
  autoTransferPayroll: true,
  autoMaintenanceExpense: true,
  autoLibraryFee: true,
  annualLeaveDays: 30,
  lateDeductionRate: 2,
  gracePeriod: true,
  fingerprintSync: true,
  admissionStatus: "مفتوح للتسجيل الإلكتروني",
  maxClassSize: 25,
  reqBirthCert: true,
  reqVaccine: true,
  reqPrevCert: true,
  reqFamilyCard: true,
  footerText: "هذه الوثيقة معتمدة ومستخرجة من نظام مدارس الإلكتروني",
  defaultTemplate: "جدول مضغوط مع تكرار الترويسة",
  rowsPerBatch: "60 صف",
  qrCodeUsage: "مفعل لكل الشهادات والفواتير",
  headerEntity: "وزارة التربية والتعليم",
  headerDepartment: "الإدارة التعليمية",
  qrVerifyUrl: "https://school.example.sd/verify",
  qrExpiry: "سنة كاملة",
  qrIncludeId: true,
  themeMode: "system",
  primaryColor: "#0ea5e9",
  language: "ar",
  dateFormat: "DD/MM/YYYY",
  defaultChannels: { email: true, sms: false, push: true },
  mobileLoginPolicy: "رمز OTP عبر SMS أو WhatsApp",
  notifSync: "لحظي للغياب والفواتير والدرجات",
  parentViewLimit: true,
  teacherViewLimit: true,
  hideFinancial: true,
  logMobileActivity: true,
  apiKey: "sk_live_school_1A2B3C4D",
  webhookUrl: "https://example.com/school-webhook",
  whStudentCreated: true,
  whInvoicePaid: true,
  whExamUpdated: true,
  whTransportChanged: true,
  apiRateLimit: 120,
  apiAccessScope: "قراءة وكتابة حسب الصلاحيات",
  apiAllowedIps: "",
  passwordPolicy: "معقدة (حروف، أرقام، رموز)",
  sessionTimeout: "بعد 30 دقيقة من الخمول",
  force2FA: true,
  lockAfter5Fails: true,
  paymentGateway: "none",
};
// --- Initial Mock Data ---
const initialStudents: Student[] = [
  { id: "STU-1001", name: "أحمد محمد محمود", dob: "2015-05-12", nationalId: "1029384756", guardianName: "محمد محمود", stage: "primary", grade: "الصف الأول الابتدائي", sectionId: "SEC-1001", gender: "ذكر", status: "نشط", bloodType: "O+", guardianPhone: "0501234567" },
  { id: "STU-1002", name: "سارة خالد العتيبي", dob: "2018-02-15", nationalId: "1098765432", guardianName: "خالد العتيبي", stage: "kindergarten", grade: "روضة 2", gender: "أنثى", status: "نشط", bloodType: "A+", medicalNotes: "حساسية من الفول السوداني", guardianPhone: "0559876543" },
  { id: "STU-1003", name: "عمر فهد العتيبي", dob: "2008-09-10", nationalId: "1002003004", guardianName: "فهد العتيبي", stage: "high", grade: "الصف الأول الثانوي", major: "science", elective: "حاسب آلي" }
];

const initialStudentEnrollments: StudentEnrollment[] = [
  { id: "ENR-1001", studentId: "STU-1001", academicYearId: "Y-1001", stage: "primary", grade: "الصف الأول الابتدائي", sectionId: "SEC-1001", status: "نشط", enrollmentDate: "2023-08-01" },
  { id: "ENR-1002", studentId: "STU-1002", academicYearId: "Y-1001", stage: "kindergarten", grade: "روضة 2", status: "نشط", enrollmentDate: "2023-08-01" },
  { id: "ENR-1003", studentId: "STU-1003", academicYearId: "Y-1001", stage: "high", grade: "الصف الأول الثانوي", major: "science", elective: "حاسب آلي", status: "نشط", enrollmentDate: "2023-08-01" }
];

const initialInvoices: Invoice[] = [
  { id: "INV-1001", studentId: "STU-1001", studentName: "أحمد محمد محمود", title: "الرسوم الدراسية - القسط الأول", amount: 5000, netAmount: 5000, discountAmount: 0, paid: 5000, issueDate: "2023-08-01", dueDate: "2023-09-01", status: "paid", stage: "primary" },
  { id: "INV-1002", studentId: "STU-1002", studentName: "سارة خالد العتيبي", title: "الرسوم الدراسية - القسط الأول", amount: 6000, netAmount: 6000, discountAmount: 0, paid: 3000, issueDate: "2023-08-01", dueDate: "2023-09-01", status: "partial", stage: "kindergarten" },
  { id: "INV-1003", studentId: "STU-1003", studentName: "عمر فهد العتيبي", title: "الرسوم الدراسية - القسط الأول", amount: 8000, netAmount: 8000, discountAmount: 0, paid: 0, issueDate: "2023-09-01", dueDate: "2023-10-01", status: "issued", stage: "high" },
];

const initialFeeStructures: FeeStructure[] = [
  { id: "FEE-001", name: "الرسوم الدراسية - ابتدائي", amount: 15000, type: "tuition", stage: "primary", isMandatory: true },
  { id: "FEE-002", name: "الرسوم الدراسية - متوسط", amount: 18000, type: "tuition", stage: "middle", isMandatory: true },
  { id: "FEE-003", name: "رسوم النقل (اتجاهين)", amount: 3000, type: "transport", stage: "all", isMandatory: false },
  { id: "FEE-004", name: "رسوم التسجيل", amount: 1000, type: "registration", stage: "all", isMandatory: true },
];

const initialDiscounts: Discount[] = [
  { id: "DIS-001", name: "خصم الإخوة", type: "percentage", value: 10, description: "يخصم 10% للأخ الثاني فما فوق" },
  { id: "DIS-002", name: "خصم أبناء المعلمين", type: "percentage", value: 25, description: "يخصم 25% من الرسوم الدراسية لأبناء العاملين" },
  { id: "DIS-003", name: "منحة تفوق", type: "fixed", value: 5000, description: "خصم مقطوع للطلاب الأوائل" },
];

const initialPayments: Payment[] = [
  { id: "PAY-001", invoiceId: "INV-1001", studentId: "STU-1001", amount: 5000, date: "2023-08-15", method: "bank_transfer", referenceNo: "TRX-98765" },
  { id: "PAY-002", invoiceId: "INV-1002", studentId: "STU-1002", amount: 3000, date: "2023-08-20", method: "cash" },
];

const initialExpenseCategories: ExpenseCategory[] = [
  { id: "EXPCAT-1", name: "رواتب الموظفين والمعلمين" },
  { id: "EXPCAT-2", name: "إيجارات" },
  { id: "EXPCAT-3", name: "فواتير الكهرباء والمياه" },
  { id: "EXPCAT-4", name: "صيانة وتطوير" },
  { id: "EXPCAT-5", name: "أدوات وقرطاسية" },
];

const initialExpenses: Expense[] = [
  { id: "EXP-001", title: "فاتورة الكهرباء - أغسطس", amount: 4500, date: "2023-09-02", categoryId: "EXPCAT-3", beneficiary: "شركة الكهرباء", method: "bank_transfer" },
  { id: "EXP-002", title: "صيانة أجهزة التكييف", amount: 2000, date: "2023-09-10", categoryId: "EXPCAT-4", beneficiary: "مؤسسة الصيانة", method: "cash" },
];

const initialBooks: Book[] = [
  { id: "B-1001", title: "تاريخ الأمم والملوك", author: "الطبري", category: "تاريخ", copies: 5, available: 3, stage: "high" },
  { id: "B-1002", title: "مقدمة ابن خلدون", author: "ابن خلدون", category: "علم اجتماع", copies: 3, available: 0, stage: "high" },
  { id: "B-1003", title: "قصص الأنبياء للأطفال", author: "ابن كثير", category: "تاريخ", copies: 10, available: 8, stage: "primary" },
  { id: "B-1004", title: "ألوان وحروف", author: "وزارة التعليم", category: "مناهج", copies: 20, available: 20, stage: "kindergarten" },
];

const initialLibraryIssues: LibraryIssue[] = [
  { id: "IS-001", bookId: "B-1002", bookTitle: "مقدمة ابن خلدون", studentId: "STU-1003", studentName: "عمر فهد العتيبي", issueDate: "2023-10-01", dueDate: "2023-10-15", status: "active", stage: "high" },
];

const initialInventoryItems: InventoryItem[] = [
  { id: "ITM-001", name: "زي مدرسي مقاس S", category: "زي مدرسي", quantity: 150, price: "120 {currency}", status: "available" },
  { id: "ITM-002", name: "حزمة كتب الصف الأول الثانوي", category: "كتب ومقررات", quantity: 10, price: "350 {currency}", status: "low_stock" },
  { id: "ITM-003", name: "ألوان خشبية", category: "قرطاسية", quantity: 0, price: "15 {currency}", status: "out_of_stock" },
];

const initialInventoryTransactions: InventoryTransaction[] = [
  { id: "TRX-001", type: "issue", itemId: "ITM-002", itemName: "حزمة كتب الصف الأول الثانوي", quantity: 1, to: "عمر فهد العتيبي", date: "2023-10-10", by: "أمين المستودع" },
];

const initialStaff: Staff[] = [
  { id: "EMP-1001", name: "خالد عبدالرحمن", role: "معلم رياضيات", department: "الشؤون الأكاديمية", status: "active", stage: "high", basicSalary: 8500, allowance: 1500, deduction: 0 },
  { id: "EMP-1002", name: "منيرة الدوسري", role: "مربية أطفال", department: "رياض الأطفال", status: "active", stage: "kindergarten", basicSalary: 6000, allowance: 1000, deduction: 300 },
  { id: "EMP-1004", name: "أحمد المعلم", role: "معلم صف", department: "الصفوف الأولية", status: "active", stage: "primary", basicSalary: 7500, allowance: 1200, deduction: 0 },
  { id: "EMP-1005", name: "فاطمة الزهراء", role: "معلم علوم", department: "العلوم", status: "active", stage: "middle", basicSalary: 8000, allowance: 1000, deduction: 100 },
  { id: "EMP-1003", name: "سالم المري", role: "حارس أمن", department: "الخدمات العامة", status: "active", stage: "all", basicSalary: 4000, allowance: 500, deduction: 0 },
];

const initialEmployeeAssignments: EmployeeAssignment[] = [
  { id: "EA-1001", employeeId: "EMP-1001", academicYearId: "Y-1001", stage: "high", role: "معلم رياضيات", department: "الشؤون الأكاديمية", status: "active", basicSalary: 8500, allowance: 1500, deduction: 0 },
  { id: "EA-1002", employeeId: "EMP-1002", academicYearId: "Y-1001", stage: "kindergarten", role: "مربية أطفال", department: "رياض الأطفال", status: "active", basicSalary: 6000, allowance: 1000, deduction: 300 },
  { id: "EA-1004", employeeId: "EMP-1004", academicYearId: "Y-1001", stage: "primary", role: "معلم صف", department: "الصفوف الأولية", status: "active", basicSalary: 7500, allowance: 1200, deduction: 0 },
  { id: "EA-1005", employeeId: "EMP-1005", academicYearId: "Y-1001", stage: "middle", role: "معلم علوم", department: "العلوم", status: "active", basicSalary: 8000, allowance: 1000, deduction: 100 },
  { id: "EA-1003", employeeId: "EMP-1003", academicYearId: "Y-1001", stage: "all", role: "حارس أمن", department: "الخدمات العامة", status: "active", basicSalary: 4000, allowance: 500, deduction: 0 },
];

const initialClinicVisits: ClinicVisit[] = [
  { id: "CV-001", studentId: "STU-1002", studentName: "سارة خالد السعيد", date: "2023-10-15", symptoms: "ارتفاع في درجة الحرارة", diagnosis: "حمى خفيفة", actionTaken: "إعطاء خافض حرارة والاتصال بولي الأمر", stage: "kindergarten" }
];

const initialDiscipline: DisciplineIncident[] = [];

const initialSections: Section[] = [
  { id: "SEC-101", name: "أ", grade: "الصف الأول", capacity: 25, stage: "primary" },
  { id: "SEC-102", name: "ب", grade: "الصف الأول", capacity: 25, stage: "primary" },
  { id: "SEC-103", name: "أ", grade: "الصف الثاني", capacity: 25, stage: "primary" },
  { id: "SEC-104", name: "أ", grade: "الصف الثالث", capacity: 25, stage: "primary" },
  { id: "SEC-105", name: "أ", grade: "الصف الرابع", capacity: 25, stage: "primary" },
  { id: "SEC-201", name: "أ", grade: "الصف الأول المتوسط", capacity: 25, stage: "middle" },
  { id: "SEC-301", name: "1", grade: "الصف الأول الثانوي", capacity: 30, stage: "high" },
];

const initialScheduleSlots: ScheduleSlot[] = [];

const initialExams: Exam[] = [];
const initialExamSubjects: ExamSubject[] = [];
const initialExamResults: ExamResult[] = [];

const initialSubjects: Subject[] = [
  { id: "SUB-101", name: "الرياضيات", code: "MATH101", creditHours: 5, stage: "primary", grades: ["الصف الأول", "الصف الثاني", "الصف الثالث", "الصف الرابع", "الصف الخامس", "الصف السادس"] },
  { id: "SUB-102", name: "العلوم", code: "SCI101", creditHours: 4, stage: "primary", grades: ["الصف الرابع", "الصف الخامس", "الصف السادس"], fee: 500 },
  { id: "SUB-103", name: "اللغة العربية", code: "ARAB101", creditHours: 6, stage: "primary", grades: ["الصف الأول", "الصف الثاني", "الصف الثالث", "الصف الرابع", "الصف الخامس", "الصف السادس"] },
  { id: "SUB-104", name: "القرآن الكريم", code: "ISL101", creditHours: 3, stage: "all" },
  { id: "SUB-105", name: "الفيزياء", code: "PHY101", creditHours: 4, stage: "high", grades: ["الصف الأول الثانوي", "الصف الثاني الثانوي", "الصف الثالث الثانوي"], fee: 800 },
  { id: "SUB-106", name: "الكيمياء", code: "CHEM101", creditHours: 4, stage: "high", grades: ["الصف الأول الثانوي", "الصف الثاني الثانوي", "الصف الثالث الثانوي"], fee: 800 },
  { id: "SUB-107", name: "لغتي الجميلة", code: "ARAB100", creditHours: 5, stage: "primary", grades: ["الصف الأول", "الصف الثاني", "الصف الثالث"] },
];

const initialAccounts: Account[] = [
  // الأصول - Assets
  { id: "ACC-101", name: "الصندوق (Cash)", type: "asset", code: "101", isSystemAccount: true, description: "النقدية السائلة بالصندوق" },
  { id: "ACC-102", name: "الحساب البنكي (Bank)", type: "asset", code: "102", isSystemAccount: true },
  { id: "ACC-103", name: "ذمم الطلاب", type: "asset", code: "103", isSystemAccount: true, description: "الرسوم المستحقة على الطلاب غير المسددة" },
  { id: "ACC-104", name: "سلف الموظفين", type: "asset", code: "104", isSystemAccount: true },
  
  // الخصوم (الالتزامات) - Liabilities
  { id: "ACC-201", name: "مستحقات الموظفين", type: "liability", code: "201", isSystemAccount: true, description: "الرواتب المستحقة غير المدفوعة" },
  { id: "ACC-202", name: "الموردين والشركات", type: "liability", code: "202", isSystemAccount: true, description: "مستحقات لشركات خارجية" },
  
  // الإيرادات - Revenues
  { id: "ACC-401", name: "إيرادات الرسوم الدراسية", type: "revenue", code: "401", isSystemAccount: true },
  { id: "ACC-402", name: "إيرادات رسوم التسجيل", type: "revenue", code: "402", isSystemAccount: true },
  { id: "ACC-403", name: "إيرادات الأنشطة والخدمات", type: "revenue", code: "403", isSystemAccount: true, description: "تشمل النقل، الزي، الكتب" },
  
  // المصروفات - Expenses
  { id: "ACC-501", name: "الرواتب والأجور", type: "expense", code: "501", isSystemAccount: true },
  { id: "ACC-502", name: "المصروفات التشغيلية", type: "expense", code: "502", isSystemAccount: true, description: "الصيانة، الفواتير، المشتريات" },
];

const initialJournalEntries: JournalEntry[] = [];
const initialJournalLines: JournalLine[] = [];


const initialAcademicYears: AcademicYear[] = [
  { id: "Y-1001", name: "١٤٤٥ هـ", startDate: "2023-08-20", endDate: "2024-06-10", isCurrent: false },
  { id: "Y-1002", name: "١٤٤٦ هـ", startDate: "2024-08-18", endDate: "2025-06-15", isCurrent: true },
];

const initialTeachingAssignments: TeachingAssignment[] = [];

const initialMaintenanceRequests: MaintenanceRequest[] = [
  { id: "MR-1001", title: "إصلاح مكيف", description: "مكيف معطل في المعمل", location: "معمل الحاسب", priority: "high", status: "new", costEstimate: 500, dateRequested: "2023-10-20" }
];
const initialRooms: Room[] = [
  { id: "RM-101", name: "المعمل الرئيسي", building: "المبنى أ", floor: "الأول", type: "lab", capacity: 30, status: "available" }
];
const initialStaffEvaluations: StaffEvaluation[] = [
  { id: "SE-1001", staffId: "EMP-1001", staffName: "خالد عبدالرحمن", period: "الفصل الأول", evaluator: "المدير", date: "2023-11-01", criteria: { commitment: 5, performance: 4, cooperation: 5, creativity: 4 }, overallScore: 4.5, notes: "أداء ممتاز" }
];
const initialStaffContracts: StaffContract[] = [
  { id: "SC-1001", staffId: "EMP-1001", staffName: "خالد عبدالرحمن", type: "full_time", startDate: "2022-08-01", endDate: "2024-08-01", basicSalary: 8500, status: "active" }
];
const initialStaffLeaves: StaffLeave[] = [
  { id: "SL-1001", staffId: "EMP-1001", staffName: "خالد عبدالرحمن", type: "sick", startDate: "2023-10-15", endDate: "2023-10-16", days: 2, status: "approved" }
];
const initialActivityLogs: ActivityLog[] = [
  { id: "AL-1001", user: "أحمد العتيبي", action: "تسجيل دخول", entity: "النظام", details: "نجاح تسجيل الدخول", date: "2023-10-20T08:00:00Z" }
];

export interface UserAccount {
  id: string;
  username: string;
  fullName: string;
  role: string;
  status: "active" | "disabled";
  lastLogin: string;
}

const initialUsers: UserAccount[] = [
  { id: "U-1001", username: "admin", fullName: "أحمد العتيبي", role: "مدير عام", status: "active", lastLogin: "2026-06-13 09:42" },
  { id: "U-1002", username: "principal01", fullName: "خالد القحطاني", role: "مدير مدرسة", status: "active", lastLogin: "2026-06-13 08:01" },
  { id: "U-1003", username: "registrar01", fullName: "نوال الزهراني", role: "أمين تسجيل", status: "active", lastLogin: "2026-06-12 14:22" },
  { id: "U-1004", username: "t.mona", fullName: "منى الزهراني", role: "معلم", status: "active", lastLogin: "2026-06-13 07:11" },
  { id: "U-1005", username: "g.saad", fullName: "سعد الحربي", role: "ولي أمر", status: "disabled", lastLogin: "2026-05-30 20:30" },
];

// --- Context ---
interface GlobalStoreContextType {
  // All Data
  allStudents: Student[];
  allDeletedStudents: Student[];
  allStudentEnrollments: StudentEnrollment[];
  allEmployeeAssignments: EmployeeAssignment[];
  allInvoices: Invoice[];
  allFeeStructures: FeeStructure[];
  allDiscounts: Discount[];
  allPayments: Payment[];
  allExpenses: Expense[];
  allExpenseCategories: ExpenseCategory[];
  allAccounts: Account[];
  allJournalEntries: JournalEntry[];
  allJournalLines: JournalLine[];
  allAuditLogs: AuditLog[];
  allBooks: Book[];
  allLibraryIssues: LibraryIssue[];
  allInventoryItems: InventoryItem[];
  allInventoryTransactions: InventoryTransaction[];
  allStaff: Staff[];
  allClinicVisits: ClinicVisit[];
  allDisciplineIncidents: DisciplineIncident[];
  allAttendanceSessions: AttendanceSession[];
  allAttendanceRecords: AttendanceRecord[];
  allAttendanceExcuses: AttendanceExcuse[];
  allBehaviorTransactions: BehaviorTransaction[];
  allDisciplineCategories: DisciplineCategory[];
  allDisciplineActions: DisciplineAction[];
  allSections: Section[];
  allExams: Exam[];
  allExamSubjects: ExamSubject[];
  allExamResults: ExamResult[];
  allSubjects: Subject[];
  allScheduleSlots: ScheduleSlot[];
  allAcademicYears: AcademicYear[];
  allTeachingAssignments: TeachingAssignment[];

  
  allMaintenanceRequests: MaintenanceRequest[];
  allRooms: Room[];
  allStaffEvaluations: StaffEvaluation[];
  allStaffContracts: StaffContract[];
  allStaffLeaves: StaffLeave[];
  allStaffAttendance: StaffAttendanceRecord[];
  allStaffAdvances: StaffAdvance[];
  allActivityLogs: ActivityLog[];
  allUsers: UserAccount[];
  
  // Filtered by Active Stage
  activeStageStudents: Student[];
  activeStageInvoices: Invoice[];
  activeStageFeeStructures: FeeStructure[];
  activeStageBooks: Book[];
  activeStageLibraryIssues: LibraryIssue[];
  activeStageStaff: Staff[];
  activeStageStaffAttendance: StaffAttendanceRecord[];
  activeStageClinicVisits: ClinicVisit[];
  activeStageDisciplineIncidents: DisciplineIncident[];
  activeStageSections: Section[];
  activeStageExams: Exam[];
  activeStageExamSubjects: ExamSubject[];
  activeStageSubjects: Subject[];
  activeStageScheduleSlots: ScheduleSlot[];
  activeStageTeachingAssignments: TeachingAssignment[];


  // Actions
  addStudent: (student: Omit<Student, "id">) => void;
  updateStudent: (id: string, updates: Partial<Student>) => void;
  softDeleteStudent: (id: string) => void;
  restoreStudent: (id: string) => void;
  hardDeleteStudent: (id: string) => void;
  addGuardian: (g: Omit<Guardian, "id">) => void;
  updateGuardian: (id: string, updates: Partial<Guardian>) => void;
  softDeleteGuardian: (id: string) => void;
  restoreGuardian: (id: string) => void;
  hardDeleteGuardian: (id: string) => void;
  restoreItem: (type: 'student' | 'guardian' | 'staff', id: string) => void;
  hardDeleteItem: (type: 'student' | 'guardian' | 'staff', id: string) => void;
  
  // Finance methods
  addInvoice: (invoiceData: Omit<Invoice, "id" | "paid" | "status"> & { status?: Invoice["status"] }) => void;
  issueInvoice: (id: string) => void;
  cancelInvoice: (id: string) => void;
  updateInvoice: (id: string, updates: Partial<Invoice>) => void;
  deleteInvoice: (id: string) => void;
  addFeeStructure: (feeData: Omit<FeeStructure, "id">) => void;
  updateFeeStructure: (id: string, updates: Partial<FeeStructure>) => void;
  deleteFeeStructure: (id: string) => void;
  addDiscount: (discountData: Omit<Discount, "id">) => void;
  updateDiscount: (id: string, updates: Partial<Discount>) => void;
  deleteDiscount: (id: string) => void;
  addPayment: (invoiceId: string, amount: number, method: string, referenceNo?: string) => void;
  addExpense: (expenseData: Omit<Expense, "id"> & { status?: Expense["status"] }) => void;
  submitExpense: (id: string) => void;
  approveExpense: (id: string) => void;
  postExpense: (id: string) => void;
  updateExpense: (id: string, updates: Partial<Expense>) => void;
  deleteExpense: (id: string) => void;

  addJournalEntry: (entry: Omit<JournalEntry, "id">, lines: Omit<JournalLine, "id" | "journalEntryId">[]) => void;
  addAccount: (account: Omit<Account, "id">) => void;
  updateAccount: (id: string, updates: Partial<Account>) => void;
  deleteAccount: (id: string) => void;
  toggleAccountStatus: (id: string) => void;
  rolloverFinancialBalances: (fromYearId: string, toYearId: string) => void;
  addAuditLog: (log: Omit<AuditLog, "id" | "timestamp">) => void;

  addBook: (book: Omit<Book, "id" | "available">) => void;
  issueBook: (bookId: string, studentId: string) => void;
  returnBook: (issueId: string) => void;
  addInventoryItem: (item: Omit<InventoryItem, "id" | "status">) => void;
  updateInventoryItem: (id: string, updates: Partial<InventoryItem>) => void;
  deleteInventoryItem: (id: string) => void;
  processInventoryTransaction: (transaction: Omit<InventoryTransaction, "id" | "date" | "itemName">) => void;
  addStaff: (staff: Omit<Staff, "id">) => void;
  updateStaff: (id: string, updates: Partial<Staff>) => void;
  deleteStaff: (id: string) => void;
  upsertStaffAttendance: (record: StaffAttendanceRecord) => void;
  addStaffAdvance: (record: Omit<StaffAdvance, "id">) => void;
  addClinicVisit: (visit: Omit<ClinicVisit, "id" | "studentName" | "stage">) => void;
  addDisciplineIncident: (incident: Omit<DisciplineIncident, "id">) => void;
  addAttendanceSession: (session: Omit<AttendanceSession, "id">, records: Omit<AttendanceRecord, "id" | "sessionId">[]) => void;
  addBehaviorTransaction: (transaction: Omit<BehaviorTransaction, "id">) => void;
  addSection: (section: Omit<Section, "id">) => void;
  updateSection: (id: string, updates: Partial<Section>) => void;
  deleteSection: (id: string) => void;
  
  currency: string;
  setCurrency: (c: string) => void;
  
  addExam: (exam: Omit<Exam, "id">) => void;
  updateExam: (id: string, updates: Partial<Exam>) => void;
  deleteExam: (id: string) => void;
  
  addExamSubject: (examSubject: Omit<ExamSubject, "id">) => void;
  updateExamSubject: (id: string, updates: Partial<ExamSubject>) => void;
  deleteExamSubject: (id: string) => void;
  
  saveExamResults: (results: Omit<ExamResult, "id">[]) => void;

  addSubject: (subject: Omit<Subject, "id">) => void;
  deleteSubject: (id: string) => void;
  updateScheduleSlot: (slot: Omit<ScheduleSlot, "id">) => void;
  clearScheduleSlot: (sectionId: string, day: string, period: number) => void;
  addAcademicYear: (year: Omit<AcademicYear, "id">) => void;
  updateAcademicYear: (id: string, updates: Partial<AcademicYear>) => void;
  addTeachingAssignment: (assignment: Omit<TeachingAssignment, "id">) => void;
  deleteTeachingAssignment: (id: string) => void;
  assignStudentToSection: (studentId: string, sectionId?: string) => void;
  promoteStudents: (promotions: { studentId: string; nextGrade: string; nextAcademicYearId: string; status: "ناجح" | "راسب" | "منقول" | "خريج" }[]) => void;
  promoteStaff: (promotions: { employeeId: string; nextRole: string; nextAcademicYearId: string; status: "active" | "on_leave" | "terminated"; basicSalary: number }[]) => void;
  generateBulkData: (count: number) => void;

  addMaintenanceRequest: (req: Omit<MaintenanceRequest, "id">) => void;
  updateMaintenanceRequest: (id: string, updates: Partial<MaintenanceRequest>) => void;
  undoMaintenanceRequest: (id: string) => void;
  deleteMaintenanceRequest: (id: string) => void;

  addRoom: (room: Omit<Room, "id">) => void;
  updateRoom: (id: string, updates: Partial<Room>) => void;
  deleteRoom: (id: string) => void;

  addStaffEvaluation: (evalData: Omit<StaffEvaluation, "id">) => void;
  addStaffContract: (contractData: Omit<StaffContract, "id">) => void;
  addStaffLeave: (leaveData: Omit<StaffLeave, "id">) => void;
  updateStaffLeave: (id: string, updates: Partial<StaffLeave>) => void;

  addActivityLog: (logData: Omit<ActivityLog, "id" | "date">) => void;

  // User Account Management
  addUser: (userData: Omit<UserAccount, "id">) => void;
  updateUser: (id: string, updates: Partial<UserAccount>) => void;
  deleteUser: (id: string) => void;

  allGuardians: Guardian[];

  // Library Distribution
  allTextbooks: Textbook[];
  allTextbookDistributions: TextbookDistribution[];
  activeStageTextbooks: Textbook[];
  activeStageDistributions: TextbookDistribution[];
  addTextbook: (tb: Omit<Textbook, "id">) => void;
  updateTextbook: (id: string, updates: Partial<Textbook>) => void;
  deleteTextbook: (id: string) => void;
  distributeTextbook: (distribution: Omit<TextbookDistribution, "id" | "date" | "status">) => void;
  removeDistribution: (id: string) => void;

  // Transport
  transportRoutes: TransportRoute[];
  transportSubscriptions: TransportSubscription[];
  addTransportRoute: (r: Omit<TransportRoute, "id">) => void;
  updateTransportRoute: (id: string, updates: Partial<TransportRoute>) => void;
  deleteTransportRoute: (id: string) => void;
  addTransportSubscription: (s: Omit<TransportSubscription, "id">) => void;
  updateTransportSubscription: (id: string, updates: Partial<TransportSubscription>) => void;
  deleteTransportSubscription: (id: string) => void;

  // Timetable
  activeStageTimetableSettings: TimetableSettings;
  updateTimetableSettings: (updates: Partial<TimetableSettings>) => void;

  systemSettings: SystemSettings;
  updateSettings: (updates: Partial<SystemSettings>) => void;

  // Notifications
  notifications: AppNotification[];
  unreadNotificationsCount: number;
  markAllNotificationsAsRead: () => void;
  deleteNotification: (id: string) => void;
  addNotification: (n: Omit<AppNotification, "id" | "timestamp" | "read">) => void;

  currentAcademicYearId: string | undefined;
}

const GlobalStoreContext = createContext<GlobalStoreContextType | undefined>(undefined);

export function GlobalStoreProvider({ children }: { children: ReactNode }) {
  const { stage: activeStage } = useStage();
  const [students, setStudents] = useState<Student[]>(initialStudents);
  const [studentEnrollments, setStudentEnrollments] = useState<StudentEnrollment[]>(initialStudentEnrollments);
  const [deletedStudents, setDeletedStudents] = useState<Student[]>([]);
  const [guardians, setGuardians] = useState<Guardian[]>([]);
  const [invoices, setInvoices] = useState<Invoice[]>(initialInvoices);
  const [feeStructures, setFeeStructures] = useState<FeeStructure[]>(initialFeeStructures);
  const [discounts, setDiscounts] = useState<Discount[]>(initialDiscounts);
  const [payments, setPayments] = useState<Payment[]>(initialPayments);
  const [expenses, setExpenses] = useState<Expense[]>(initialExpenses);
  const [expenseCategories] = useState<ExpenseCategory[]>(initialExpenseCategories);
  const [books, setBooks] = useState<Book[]>(initialBooks);
  const [libraryIssues, setLibraryIssues] = useState<LibraryIssue[]>(initialLibraryIssues);
  const [inventoryItems, setInventoryItems] = useState<InventoryItem[]>(initialInventoryItems);
  const [inventoryTransactions, setInventoryTransactions] = useState<InventoryTransaction[]>(initialInventoryTransactions);
  const [staff, setStaff] = useState<Staff[]>(initialStaff);
  const [employeeAssignments, setEmployeeAssignments] = useState<EmployeeAssignment[]>(initialEmployeeAssignments);
  const [clinicVisits, setClinicVisits] = useState<ClinicVisit[]>(initialClinicVisits);
  const [disciplineIncidents, setDisciplineIncidents] = useState<DisciplineIncident[]>([]);
  const [attendanceSessions, setAttendanceSessions] = useState<AttendanceSession[]>([]);
  const [attendanceRecords, setAttendanceRecords] = useState<AttendanceRecord[]>([]);
  const [attendanceExcuses, setAttendanceExcuses] = useState<AttendanceExcuse[]>([]);
  const [behaviorTransactions, setBehaviorTransactions] = useState<BehaviorTransaction[]>([]);
  const [disciplineCategories, setDisciplineCategories] = useState<DisciplineCategory[]>([
    { id: "DC-01", name: "غياب متكرر", type: "behavioral", severity: "medium", defaultPoints: -3, recommendedAction: "إنذار أول" },
    { id: "DC-02", name: "شغب في الفصل", type: "behavioral", severity: "high", defaultPoints: -5, recommendedAction: "استدعاء ولي الأمر" },
    { id: "DC-03", name: "تأخر دراسي", type: "academic", severity: "low", defaultPoints: -1, recommendedAction: "تنبيه" },
    { id: "DC-04", name: "مشاركة متميزة", type: "behavioral", severity: "low", defaultPoints: 5, recommendedAction: "شكر" },
    { id: "DC-05", name: "تفوق أكاديمي", type: "academic", severity: "high", defaultPoints: 10, recommendedAction: "شهادة تقدير" }
  ]);
  const [disciplineActions, setDisciplineActions] = useState<DisciplineAction[]>([]);
  const [sections, setSections] = useState<Section[]>(initialSections);
  const [exams, setExams] = useState<Exam[]>(initialExams);
  const [examSubjects, setExamSubjects] = useState<ExamSubject[]>(initialExamSubjects);
  const [examResults, setExamResults] = useState<ExamResult[]>(initialExamResults);
  const [accounts, setAccounts] = useState<Account[]>(initialAccounts);
  const [journalEntries, setJournalEntries] = useState<JournalEntry[]>(initialJournalEntries);
  const [journalLines, setJournalLines] = useState<JournalLine[]>(initialJournalLines);
  const [auditLogs, setAuditLogs] = useState<AuditLog[]>([]);
  const [currency, setCurrency] = useState(() => {
    try {
      const saved = localStorage.getItem("darasi_currency");
      return saved || "ج.س";
    } catch {
      return "ج.س";
    }
  });
  const [subjects, setSubjects] = useState<Subject[]>(initialSubjects);
  const [scheduleSlots, setScheduleSlots] = useState<ScheduleSlot[]>(initialScheduleSlots);
  const [academicYears, setAcademicYears] = useState<AcademicYear[]>(initialAcademicYears);
  const [teachingAssignments, setTeachingAssignments] = useState<TeachingAssignment[]>(initialTeachingAssignments);

  const [maintenanceRequests, setMaintenanceRequests] = useState<MaintenanceRequest[]>(initialMaintenanceRequests);
  const [rooms, setRooms] = useState<Room[]>(initialRooms);
  const [staffEvaluations, setStaffEvaluations] = useState<StaffEvaluation[]>(initialStaffEvaluations);
  const [staffContracts, setStaffContracts] = useState<StaffContract[]>(initialStaffContracts);
  const [staffLeaves, setStaffLeaves] = useState<StaffLeave[]>(initialStaffLeaves);
  const [staffAttendance, setStaffAttendance] = useState<StaffAttendanceRecord[]>([]);
  const [staffAdvances, setStaffAdvances] = useState<StaffAdvance[]>([]);
  const [activityLogs, setActivityLogs] = useState<ActivityLog[]>(initialActivityLogs);
  const [users, setUsers] = useState<UserAccount[]>(initialUsers);

  // Notifications
  const [notifications, setNotifications] = useState<AppNotification[]>([
    {
      id: "notif-1",
      title: "تنبيه: ميزانية تجاوزت الحد",
      message: "الرجاء مراجعة قسم المالية فوراً.",
      type: "danger",
      timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
      read: false
    },
    {
      id: "notif-2",
      title: "تم تسجيل ١٠ طلاب جدد",
      message: "في مرحلة رياض الأطفال.",
      type: "success",
      timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
      read: false
    }
  ]);

  const unreadNotificationsCount = useMemo(() => notifications.filter(n => !n.read).length, [notifications]);
  const markAllNotificationsAsRead = () => setNotifications(prev => prev.map(n => ({ ...n, read: true })));
  const deleteNotification = (id: string) => setNotifications(prev => prev.filter(n => n.id !== id));
  const addNotification = (n: Omit<AppNotification, "id" | "timestamp" | "read">) => {
    setNotifications(prev => [{
      ...n,
      id: `notif-${Math.random().toString(36).substr(2, 9)}`,
      timestamp: new Date().toISOString(),
      read: false
    }, ...prev]);
  };

  const [systemSettings, setSystemSettings] = useState<SystemSettings>(() => {
    try {
      const saved = localStorage.getItem("darasi_system_settings");
      if (saved) {
        return { ...defaultSettings, ...JSON.parse(saved) };
      }
    } catch (e) {
      console.error("Error loading settings:", e);
    }
    return defaultSettings;
  });
  
  useEffect(() => {
    localStorage.setItem("darasi_system_settings", JSON.stringify(systemSettings));
  }, [systemSettings]);

  useEffect(() => {
    localStorage.setItem("darasi_currency", currency);
  }, [currency]);
  
  const updateSettings = (updates: Partial<SystemSettings>) => {
    setSystemSettings(prev => ({ ...prev, ...updates }));
  };

  const [textbooks, setTextbooks] = useState<Textbook[]>([]);
  const [textbookDistributions, setTextbookDistributions] = useState<TextbookDistribution[]>([]);

  const [transportRoutes, setTransportRoutes] = useState<TransportRoute[]>([]);
  const [transportSubscriptions, setTransportSubscriptions] = useState<TransportSubscription[]>([]);



  const [timetableSettings, setTimetableSettings] = useState<TimetableSettings>({
    maxPeriodsPerDay: 7,
    breakDuration: 45,
    periodDuration: 45,
    stage: "all"
  });

  const currentAcademicYearId = useMemo(() => academicYears.find(y => y.isCurrent)?.id, [academicYears]);

  // Derived state filtered by the global active stage and active year
  const activeStageStudents = useMemo(() => {
    return studentEnrollments
      .filter(e => e.academicYearId === currentAcademicYearId && e.stage === activeStage)
      .map(e => {
        const studentIdentity = students.find(s => s.id === e.studentId);
        return { ...studentIdentity, ...e } as Student;
      });
  }, [studentEnrollments, students, currentAcademicYearId, activeStage]);
  
  const allDeletedStudents = useMemo(() => students.filter(s => s.isDeleted), [students]);
  const activeStageInvoices = useMemo(() => invoices.filter(inv => inv.stage === activeStage), [invoices, activeStage]);
  const activeStageFeeStructures = useMemo(() => feeStructures.filter(f => f.stage === "all" || f.stage === activeStage), [feeStructures, activeStage]);
  const activeStageBooks = useMemo(() => books.filter(b => b.stage === activeStage), [books, activeStage]);
  const activeStageLibraryIssues = useMemo(() => libraryIssues.filter(li => li.stage === activeStage), [libraryIssues, activeStage]);
  
  const activeStageStaff = useMemo(() => {
    return employeeAssignments
      .filter(a => a.academicYearId === currentAcademicYearId && (a.stage === activeStage || a.stage === "all"))
      .map(a => {
        const employeeIdentity = staff.find(s => s.id === a.employeeId);
        return { ...employeeIdentity, ...a } as Staff;
      });
  }, [employeeAssignments, staff, currentAcademicYearId, activeStage]);
  const activeStageStaffAttendance = useMemo(() => staffAttendance.filter(sa => activeStageStaff.some(s => s.id === sa.staffId)), [staffAttendance, activeStageStaff]);
  const activeStageClinicVisits = useMemo(() => clinicVisits.filter(cv => cv.stage === activeStage), [clinicVisits, activeStage]);
  const activeStageDisciplineIncidents = useMemo(() => {
    return disciplineIncidents.filter(di => {
      const enrollment = studentEnrollments.find(e => e.id === di.studentEnrollmentId);
      return enrollment && enrollment.stage === activeStage;
    });
  }, [disciplineIncidents, studentEnrollments, activeStage]);
  const activeStageSections = useMemo(() => sections.filter(sec => sec.stage === activeStage), [sections, activeStage]);
  const activeStageExams = useMemo(() => exams.filter(ex => ex.academicYearId === currentAcademicYearId), [exams, currentAcademicYearId]);
  const activeStageExamSubjects = useMemo(() => examSubjects.filter(sub => sub.stage === activeStage || sub.stage === "all"), [examSubjects, activeStage]);
  const activeStageSubjects = useMemo(() => subjects.filter(sub => sub.stage === activeStage || sub.stage === "all"), [subjects, activeStage]);
  const activeStageScheduleSlots = useMemo(() => scheduleSlots.filter(s => s.stage === activeStage), [scheduleSlots, activeStage]);
  const activeStageTeachingAssignments = useMemo(() => teachingAssignments.filter(ta => ta.stage === activeStage), [teachingAssignments, activeStage]);



  const activeStageTextbooks = useMemo(() => textbooks.filter(t => t.stage === activeStage), [textbooks, activeStage]);
  const activeStageDistributions = useMemo(() => textbookDistributions.filter(d => d.stage === activeStage), [textbookDistributions, activeStage]);
  const activeStageTimetableSettings = useMemo(() => timetableSettings.stage === activeStage || timetableSettings.stage === "all" ? timetableSettings : timetableSettings, [timetableSettings, activeStage]);

  // --- Actions ---
  const addStudent = (studentData: Omit<Student, "id">) => {
    const existingStudent = students.find(s => s.nationalId === studentData.nationalId);
    const newStudentId = existingStudent ? existingStudent.id : `STU-${Math.floor(1000 + Math.random() * 9000)}`;
    
    if (!existingStudent) {
      const newStudent = { ...studentData, id: newStudentId } as Student;
      setStudents((prev) => [newStudent, ...prev]);
    }

    const newEnrollment: StudentEnrollment = {
      id: `ENR-${Math.floor(1000 + Math.random() * 9000)}`,
      studentId: newStudentId,
      academicYearId: currentAcademicYearId || "",
      stage: studentData.stage,
      grade: studentData.grade,
      sectionId: studentData.sectionId,
      status: studentData.status || "نشط",
      enrollmentDate: new Date().toISOString().split("T")[0],
      major: studentData.major,
      elective: studentData.elective
    };
    setStudentEnrollments(prev => [newEnrollment, ...prev]);

    // Calculate tuition base
    const tuitionAmount = studentData.stage === "kindergarten" ? 6000 : studentData.stage === "primary" ? 5000 : studentData.stage === "middle" ? 6500 : 8000;
    
    // Calculate additional fees from subjects
    const applicableSubjects = subjects.filter(sub => 
      (sub.stage === "all" || sub.stage === studentData.stage) && 
      (!sub.grades || sub.grades.length === 0 || sub.grades.includes(studentData.grade))
    );
    const subjectFees = applicableSubjects.reduce((acc, curr) => acc + (curr.fee || 0), 0);
    
    const totalAmount = tuitionAmount + subjectFees;

    const newInvoice: Invoice = {
      id: `INV-${Math.floor(1000 + Math.random() * 9000)}`,
      studentId: newStudentId, 
      studentName: studentData.name, 
      amount: totalAmount, 
      netAmount: totalAmount, 
      discountAmount: 0, 
      paid: 0,
      dueDate: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString().split("T")[0],
      status: "issued", 
      stage: studentData.stage, 
      issueDate: new Date().toISOString().split('T')[0], 
      title: subjectFees > 0 ? "الرسوم الدراسية ورسوم المواد" : "الرسوم الدراسية"
    };
    setInvoices((prev) => [newInvoice, ...prev]);
  };

  const updateStudent = (id: string, updates: Partial<Student>) => {
    setStudents(prev => prev.map(s => s.id === id ? { ...s, ...updates } : s));
    setStudentEnrollments(prev => prev.map(e => (e.studentId === id && e.academicYearId === currentAcademicYearId) ? { ...e, ...updates } as StudentEnrollment : e));
  };

  const softDeleteStudent = (id: string) => {
    setStudents(prev => prev.map(s => s.id === id ? { ...s, isDeleted: true, deletedAt: new Date().toISOString() } : s));
  };

  const restoreStudent = (id: string) => {
    setStudents(prev => prev.map(s => s.id === id ? { ...s, isDeleted: false, deletedAt: undefined } : s));
  };

  const hardDeleteStudent = (id: string) => {
    setStudents(prev => prev.filter(s => s.id !== id));
    setStudentEnrollments(prev => prev.filter(e => e.studentId !== id));
  };

  const addGuardian = (g: Omit<Guardian, "id">) => {
    setGuardians(prev => [...prev, { ...g, id: `G-${Math.floor(1000 + Math.random() * 9000)}` }]);
  };

  const updateGuardian = (id: string, updates: Partial<Guardian>) => {
    setGuardians(prev => prev.map(g => g.id === id ? { ...g, ...updates } : g));
  };

  const softDeleteGuardian = (id: string) => {
    setGuardians(prev => prev.map(g => g.id === id ? { ...g, isDeleted: true, deletedAt: new Date().toISOString() } : g));
  };

  const restoreGuardian = (id: string) => {
    setGuardians(prev => prev.map(g => g.id === id ? { ...g, isDeleted: false, deletedAt: undefined } : g));
  };

  const hardDeleteGuardian = (id: string) => {
    setGuardians(prev => prev.filter(g => g.id !== id));
  };

  const assignStudentToSection = (studentId: string, sectionId?: string) => {
    setStudentEnrollments(prev => prev.map(e => (e.studentId === studentId && e.academicYearId === currentAcademicYearId) ? { ...e, sectionId } : e));
  };

  const promoteStudents = (promotions: { studentId: string; nextGrade: string; nextAcademicYearId: string; status: "ناجح" | "راسب" | "منقول" | "خريج" }[]) => {
    setStudentEnrollments(prev => {
      let updated = [...prev];
      promotions.forEach(promo => {
        const currentEnr = updated.find(e => e.studentId === promo.studentId && e.academicYearId === currentAcademicYearId);
        
        if (currentEnr) {
           currentEnr.status = promo.status;
        }

        updated.push({
          id: `ENR-${Math.floor(1000 + Math.random() * 9000)}`,
          studentId: promo.studentId,
          academicYearId: promo.nextAcademicYearId,
          stage: currentEnr?.stage || "primary",
          grade: promo.nextGrade,
          status: promo.status === "خريج" ? "خريج" : "نشط",
          enrollmentDate: new Date().toISOString().split("T")[0]
        });
      });
      return updated;
    });
  };

  const promoteStaff = (promotions: { employeeId: string; nextRole: string; nextAcademicYearId: string; status: "active" | "on_leave" | "terminated"; basicSalary: number }[]) => {
    setEmployeeAssignments(prev => {
      let updated = [...prev];
      promotions.forEach(promo => {
        const currentAssgn = updated.find(e => e.employeeId === promo.employeeId && e.academicYearId === currentAcademicYearId);
        
        if (currentAssgn && promo.status !== "active") {
           currentAssgn.status = promo.status;
        }

        if (promo.status !== "terminated") {
          updated.push({
            id: `EMP-ASSGN-${Math.floor(1000 + Math.random() * 9000)}`,
            employeeId: promo.employeeId,
            academicYearId: promo.nextAcademicYearId,
            role: promo.nextRole,
            department: currentAssgn?.department || "General",
            status: promo.status,
            basicSalary: promo.basicSalary,
            stage: currentAssgn?.stage || "all"
          });
        }
      });
      return updated;
    });
  };

  // --- Finance Methods ---
  const addInvoice = (invoiceData: Omit<Invoice, "id" | "paid" | "status"> & { status?: Invoice["status"] }) => {
    const id = `INV-${Math.floor(1000 + Math.random() * 9000)}`;
    const newInvoice: Invoice = { ...invoiceData, id, paid: 0, status: invoiceData.status || "issued" };
    setInvoices(prev => [newInvoice, ...prev]);

    // Create Journal Entry ONLY if issued
    if (newInvoice.status === "issued") {
      const jId = `JE-${Math.floor(10000 + Math.random() * 90000)}`;
      const je: JournalEntry = {
        id: jId,
        academicYearId: currentAcademicYearId || "",
        date: newInvoice.issueDate || new Date().toISOString().split("T")[0],
        referenceId: id,
        referenceType: "invoice",
        description: `استحقاق ${newInvoice.title} للطالب ${newInvoice.studentName}`,
        status: "posted",
        isAutoGenerated: true,
        sourceDocumentType: "invoice",
        sourceDocumentId: id
      };
      
      const amount = newInvoice.netAmount ?? newInvoice.amount;
      const jl1: JournalLine = { id: `JL-${Math.floor(10000 + Math.random() * 90000)}`, journalEntryId: jId, accountId: "ACC-103", debit: amount, credit: 0, studentId: newInvoice.studentId, referenceId: newInvoice.studentId, referenceType: 'student' };
      const jl2: JournalLine = { id: `JL-${Math.floor(10000 + Math.random() * 90000)}`, journalEntryId: jId, accountId: "ACC-401", debit: 0, credit: amount, studentId: newInvoice.studentId, referenceId: newInvoice.studentId, referenceType: 'student' };
      
      setJournalEntries(prev => [je, ...prev]);
      setJournalLines(prev => [jl1, jl2, ...prev]);
    }
  };

  const issueInvoice = (id: string) => {
    const invoice = invoices.find(i => i.id === id);
    if (!invoice || invoice.status !== "draft") return;

    setInvoices(prev => prev.map(inv => inv.id === id ? { ...inv, status: "issued", issueDate: new Date().toISOString().split('T')[0] } : inv));

    // Create Journal Entry
    const jId = `JE-${Math.floor(10000 + Math.random() * 90000)}`;
    const je: JournalEntry = {
      id: jId,
      academicYearId: currentAcademicYearId || "",
      date: new Date().toISOString().split("T")[0],
      referenceId: id,
      referenceType: "invoice",
      description: `استحقاق ${invoice.title} للطالب ${invoice.studentName}`,
      status: "posted",
      isAutoGenerated: true,
      sourceDocumentType: "invoice",
      sourceDocumentId: id
    };
    
    const amount = invoice.netAmount ?? invoice.amount;
    const jl1: JournalLine = { id: `JL-${Math.floor(10000 + Math.random() * 90000)}`, journalEntryId: jId, accountId: "ACC-103", debit: amount, credit: 0, studentId: invoice.studentId, referenceId: invoice.studentId, referenceType: 'student' };
    const jl2: JournalLine = { id: `JL-${Math.floor(10000 + Math.random() * 90000)}`, journalEntryId: jId, accountId: "ACC-401", debit: 0, credit: amount, studentId: invoice.studentId, referenceId: invoice.studentId, referenceType: 'student' };
    
    setJournalEntries(prev => [je, ...prev]);
    setJournalLines(prev => [jl1, jl2, ...prev]);
  };

  const cancelInvoice = (id: string) => {
    const invoice = invoices.find(i => i.id === id);
    if (!invoice || invoice.status === "cancelled" || invoice.paid > 0) return; // Cannot cancel paid invoices directly without a credit note
    setInvoices(prev => prev.map(inv => inv.id === id ? { ...inv, status: "cancelled" } : inv));
    
    // Reverse Journal Entry if it was issued
    if (invoice.status === "issued") {
      const jId = `JE-${Math.floor(10000 + Math.random() * 90000)}`;
      const je: JournalEntry = {
        id: jId,
        academicYearId: currentAcademicYearId || "",
        date: new Date().toISOString().split("T")[0],
        referenceId: id,
        referenceType: "invoice",
        description: `إلغاء استحقاق ${invoice.title} للطالب ${invoice.studentName}`,
        status: "posted",
        isAutoGenerated: true,
        sourceDocumentType: "invoice",
        sourceDocumentId: id
      };
      
      const amount = invoice.netAmount ?? invoice.amount;
      const jl1: JournalLine = { id: `JL-${Math.floor(10000 + Math.random() * 90000)}`, journalEntryId: jId, accountId: "ACC-103", debit: 0, credit: amount, studentId: invoice.studentId, referenceId: invoice.studentId, referenceType: 'student' }; // Credit AR
      const jl2: JournalLine = { id: `JL-${Math.floor(10000 + Math.random() * 90000)}`, journalEntryId: jId, accountId: "ACC-401", debit: amount, credit: 0, studentId: invoice.studentId, referenceId: invoice.studentId, referenceType: 'student' }; // Debit Revenue
      
      setJournalEntries(prev => [je, ...prev]);
      setJournalLines(prev => [jl1, jl2, ...prev]);
    }
  };

  const updateInvoice = (id: string, updates: Partial<Invoice>) => {
    setInvoices(prev => prev.map(inv => {
      if (inv.id === id) {
        const updated = { ...inv, ...updates };
        // Status overrides only apply if not draft or cancelled
        if (updated.status !== "draft" && updated.status !== "cancelled") {
          if (updated.paid >= (updated.netAmount || updated.amount)) {
            updated.status = "paid";
          } else if (updated.paid > 0) {
            updated.status = "partial";
          } else {
            updated.status = "issued";
          }
        }
        return updated;
      }
      return inv;
    }));
  };

  const deleteInvoice = (id: string) => {
    setInvoices(prev => prev.filter(inv => inv.id !== id));
    // Optionally delete associated payments
    setPayments(prev => prev.filter(p => p.invoiceId !== id));
  };

  const addFeeStructure = (feeData: Omit<FeeStructure, "id">) => setFeeStructures(prev => [{ ...feeData, id: `FEE-${Math.floor(1000 + Math.random() * 9000)}` }, ...prev]);
  const updateFeeStructure = (id: string, updates: Partial<FeeStructure>) => setFeeStructures(prev => prev.map(f => f.id === id ? { ...f, ...updates } : f));
  const deleteFeeStructure = (id: string) => setFeeStructures(prev => prev.filter(f => f.id !== id));

  const addDiscount = (discountData: Omit<Discount, "id">) => setDiscounts(prev => [{ ...discountData, id: `DIS-${Math.floor(1000 + Math.random() * 9000)}` }, ...prev]);
  const updateDiscount = (id: string, updates: Partial<Discount>) => setDiscounts(prev => prev.map(d => d.id === id ? { ...d, ...updates } : d));
  const deleteDiscount = (id: string) => setDiscounts(prev => prev.filter(d => d.id !== id));

  const addJournalEntry = (entry: Omit<JournalEntry, "id">, lines: Omit<JournalLine, "id" | "journalEntryId">[]) => {
    const jId = `JE-${Math.floor(10000 + Math.random() * 90000)}`;
    const je = { ...entry, id: jId } as JournalEntry;
    setJournalEntries(prev => [je, ...prev]);
    
    const jLines = lines.map(l => ({ ...l, id: `JL-${Math.floor(10000 + Math.random() * 90000)}`, journalEntryId: jId } as JournalLine));
    setJournalLines(prev => [...jLines, ...prev]);
  };

  const addAccount = (account: Omit<Account, "id">) => {
    const newAcc = { ...account, id: `ACC-${Math.floor(1000 + Math.random() * 9000)}`, isActive: true } as Account;
    setAccounts(prev => [...prev, newAcc]);
    addAuditLog({ action: "create", details: `حساب جديد: ${account.name}`, entityType: 'system', entityId: newAcc.id, userId: 'SYS', userName: 'المستخدم الحالي' });
  };

  const updateAccount = (id: string, updates: Partial<Account>) => {
    setAccounts(prev => prev.map(a => a.id === id ? { ...a, ...updates } : a));
    addAuditLog({ action: "update", details: `تحديث بيانات الحساب ${id}`, entityType: 'system', entityId: id, userId: 'SYS', userName: 'المستخدم الحالي' });
  };

  const deleteAccount = (id: string) => {
    const acc = accounts.find(a => a.id === id);
    if (acc?.isSystemAccount) return;
    setAccounts(prev => prev.filter(a => a.id !== id));
    addAuditLog({ action: "delete", details: `تم حذف الحساب ${id}`, entityType: 'system', entityId: id, userId: 'SYS', userName: 'المستخدم الحالي' });
  };

  const toggleAccountStatus = (id: string) => {
    const acc = accounts.find(a => a.id === id);
    if (acc?.isSystemAccount) return;
    setAccounts(prev => prev.map(a => a.id === id ? { ...a, isActive: !(a.isActive ?? true) } : a));
    addAuditLog({ action: "update", details: `تغيير حالة الحساب ${id}`, entityType: 'system', entityId: id, userId: 'SYS', userName: 'المستخدم الحالي' });
  };

  const rolloverFinancialBalances = (fromYearId: string, toYearId: string) => {
    // Calculate balances for each student in fromYearId
    const entriesFrom = journalEntries.filter(e => e.academicYearId === fromYearId);
    const entryIds = new Set(entriesFrom.map(e => e.id));
    const arLines = journalLines.filter(l => entryIds.has(l.journalEntryId) && l.accountId === "ACC-103" && l.studentId);
    
    const balances: Record<string, number> = {};
    for (const l of arLines) {
      if (!l.studentId) continue;
      balances[l.studentId] = (balances[l.studentId] || 0) + (l.debit - l.credit);
    }
    
    // Create Opening Balance Entry in toYearId
    const jId = `JE-${Math.floor(10000 + Math.random() * 90000)}`;
    const je: JournalEntry = {
      id: jId,
      academicYearId: toYearId,
      date: new Date().toISOString().split("T")[0],
      referenceType: "manual",
      description: "رصيد افتتاحي مرحل من السنة السابقة",
      status: "posted"
    };

    let totalDebit = 0;
    let totalCredit = 0;
    const lines: JournalLine[] = [];
    
    for (const [studentId, balance] of Object.entries(balances)) {
      if (balance === 0) continue;
      const jlId = `JL-${Math.floor(10000 + Math.random() * 90000)}`;
      if (balance > 0) {
        lines.push({ id: jlId, journalEntryId: jId, accountId: "ACC-103", debit: balance, credit: 0, studentId });
        totalDebit += balance;
      } else {
        lines.push({ id: jlId, journalEntryId: jId, accountId: "ACC-103", debit: 0, credit: -balance, studentId });
        totalCredit += -balance;
      }
    }
    
    if (lines.length > 0) {
      // Balance the entry with Retained Earnings or a general Opening Balance account. 
      // For simplicity, we credit/debit Retained Earnings/Equity (assume ACC-101 for now or a new one)
      const diff = totalDebit - totalCredit;
      const jlBalId = `JL-${Math.floor(10000 + Math.random() * 90000)}`;
      if (diff > 0) {
         lines.push({ id: jlBalId, journalEntryId: jId, accountId: "ACC-402", debit: 0, credit: diff }); // Credit some account to balance
      } else if (diff < 0) {
         lines.push({ id: jlBalId, journalEntryId: jId, accountId: "ACC-402", debit: -diff, credit: 0 }); // Debit some account to balance
      }
      
      setJournalEntries(prev => [je, ...prev]);
      setJournalLines(prev => [...lines, ...prev]);
    }
  };

  const addAuditLog = (logData: Omit<AuditLog, "id" | "timestamp">) => {
    const newLog: AuditLog = {
      ...logData,
      id: `AL-${Math.floor(100000 + Math.random() * 900000)}`,
      timestamp: new Date().toISOString()
    };
    setAuditLogs(prev => [newLog, ...prev]);
  };

  const addExpense = (expenseData: Omit<Expense, "id"> & { status?: Expense["status"] }) => {
    const id = `EXP-${Math.floor(1000 + Math.random() * 9000)}`;
    const newExpense: Expense = { ...expenseData, id, status: expenseData.status || "draft" };
    setExpenses(prev => [newExpense, ...prev]);

    // Create Journal Entry only if posted immediately (e.g. automated HR processes might pass status="posted")
    if (newExpense.status === "posted") {
      const jId = `JE-${Math.floor(10000 + Math.random() * 90000)}`;
      const je: JournalEntry = {
        id: jId,
        academicYearId: currentAcademicYearId || "",
        date: newExpense.date,
        referenceId: id,
        referenceType: "expense",
        description: `صرف ${newExpense.title} - المستفيد: ${newExpense.beneficiary}`,
        status: "posted",
        isAutoGenerated: true,
        sourceDocumentType: "expense",
        sourceDocumentId: id
      };
      
      const amount = newExpense.amount;
      const creditAcc = newExpense.method === 'cash' ? 'ACC-101' : 'ACC-102';
      const jl1: JournalLine = { id: `JL-${Math.floor(10000 + Math.random() * 90000)}`, journalEntryId: jId, accountId: "ACC-502", debit: amount, credit: 0 };
      const jl2: JournalLine = { id: `JL-${Math.floor(10000 + Math.random() * 90000)}`, journalEntryId: jId, accountId: creditAcc, debit: 0, credit: amount };
      
      setJournalEntries(prev => [je, ...prev]);
      setJournalLines(prev => [jl1, jl2, ...prev]);
    }
  };

  const submitExpense = (id: string) => {
    setExpenses(prev => prev.map(e => e.id === id && (e.status === "draft" || !e.status) ? { ...e, status: "submitted" } : e));
  };

  const approveExpense = (id: string) => {
    setExpenses(prev => prev.map(e => e.id === id && e.status === "submitted" ? { ...e, status: "approved" } : e));
  };

  const postExpense = (id: string) => {
    const expense = expenses.find(e => e.id === id);
    if (!expense || expense.status !== "approved") return;

    setExpenses(prev => prev.map(e => e.id === id ? { ...e, status: "posted" } : e));

    // Create Journal Entry
    const jId = `JE-${Math.floor(10000 + Math.random() * 90000)}`;
    const je: JournalEntry = {
      id: jId,
      academicYearId: currentAcademicYearId || "",
      date: new Date().toISOString().split("T")[0], // Date of posting
      referenceId: id,
      referenceType: "expense",
      description: `ترحيل مصروف: ${expense.title} - المستفيد: ${expense.beneficiary}`,
      status: "posted",
      isAutoGenerated: true,
      sourceDocumentType: "expense",
      sourceDocumentId: id
    };
    
    const amount = expense.amount;
    const creditAcc = expense.method === 'cash' ? 'ACC-101' : 'ACC-102';
    const jl1: JournalLine = { id: `JL-${Math.floor(10000 + Math.random() * 90000)}`, journalEntryId: jId, accountId: "ACC-502", debit: amount, credit: 0 };
    const jl2: JournalLine = { id: `JL-${Math.floor(10000 + Math.random() * 90000)}`, journalEntryId: jId, accountId: creditAcc, debit: 0, credit: amount };
    
    setJournalEntries(prev => [je, ...prev]);
    setJournalLines(prev => [jl1, jl2, ...prev]);
  };
  const updateExpense = (id: string, updates: Partial<Expense>) => setExpenses(prev => prev.map(e => e.id === id ? { ...e, ...updates } : e));
  const deleteExpense = (id: string) => setExpenses(prev => prev.filter(e => e.id !== id));

  const addPayment = (invoiceId: string, amount: number, method: string = "cash", referenceNo?: string) => {
    const paymentId = `PAY-${Math.floor(1000 + Math.random() * 9000)}`;
    const studentId = invoices.find(i => i.id === invoiceId)?.studentId || "";
    const payment: Payment = {
      id: paymentId,
      invoiceId,
      studentId,
      amount,
      date: new Date().toISOString().split("T")[0],
      method: method as any,
      referenceNo
    };
    
    setPayments(prev => [payment, ...prev]);

    // Create Journal Entry
    const jId = `JE-${Math.floor(10000 + Math.random() * 90000)}`;
    const je: JournalEntry = {
      id: jId,
      academicYearId: currentAcademicYearId || "",
      date: payment.date,
      referenceId: paymentId,
      referenceType: "payment",
      description: `سداد للرقم المرجعي ${referenceNo || invoiceId}`,
      status: "posted",
      isAutoGenerated: true,
      sourceDocumentType: "payment",
      sourceDocumentId: paymentId
    };
    
    // Debit Cash/Bank (ACC-101 / ACC-102), Credit AR (ACC-103)
    const debitAcc = method === 'cash' ? 'ACC-101' : 'ACC-102';
    const jl1: JournalLine = { id: `JL-${Math.floor(10000 + Math.random() * 90000)}`, journalEntryId: jId, accountId: debitAcc, debit: amount, credit: 0 };
    const jl2: JournalLine = { id: `JL-${Math.floor(10000 + Math.random() * 90000)}`, journalEntryId: jId, accountId: "ACC-103", debit: 0, credit: amount, studentId, referenceId: studentId, referenceType: 'student' };
    
    setJournalEntries(prev => [je, ...prev]);
    setJournalLines(prev => [jl1, jl2, ...prev]);

    setInvoices((prev) =>
      prev.map((inv) => {
        if (inv.id === invoiceId) {
          const newPaid = inv.paid + amount;
          const targetAmount = inv.netAmount ?? inv.amount;
          return {
            ...inv,
            paid: newPaid,
            status: newPaid >= targetAmount ? "paid" : newPaid > 0 ? "partial" : "issued",
          };
        }
        return inv;
      })
    );
  };

  const addBook = (bookData: Omit<Book, "id" | "available">) => {
    const newBook: Book = { ...bookData, id: `B-${Math.floor(1000 + Math.random() * 9000)}`, available: bookData.copies };
    setBooks(prev => [newBook, ...prev]);
  };

  const issueBook = (bookId: string, studentId: string) => {
    const book = books.find(b => b.id === bookId);
    const student = students.find(s => s.id === studentId);
    if (!book || !student || book.available <= 0) return;

    const newIssue: LibraryIssue = {
      id: `IS-${Math.floor(1000 + Math.random() * 9000)}`,
      bookId, bookTitle: book.title, studentId, studentName: student.name,
      issueDate: new Date().toISOString().split("T")[0],
      dueDate: new Date(new Date().setDate(new Date().getDate() + 14)).toISOString().split("T")[0],
      status: "active", stage: student.stage,
    };
    setLibraryIssues(prev => [newIssue, ...prev]);
    setBooks(prev => prev.map(b => b.id === bookId ? { ...b, available: b.available - 1 } : b));
  };

  const returnBook = (issueId: string) => {
    setLibraryIssues(prev => prev.map(issue => {
      if (issue.id === issueId && issue.status !== "returned") {
        setBooks(booksPrev => booksPrev.map(b => b.id === issue.bookId ? { ...b, available: b.available + 1 } : b));
        return { ...issue, status: "returned" };
      }
      return issue;
    }));
  };

  const addInventoryItem = (itemData: Omit<InventoryItem, "id" | "status">) => {
    const newItem: InventoryItem = {
      ...itemData, id: `ITM-${Math.floor(1000 + Math.random() * 9000)}`,
      status: itemData.quantity === 0 ? "out_of_stock" : itemData.quantity <= 10 ? "low_stock" : "available",
    };
    setInventoryItems(prev => [newItem, ...prev]);
  };

  const updateInventoryItem = (id: string, updates: Partial<InventoryItem>) => {
    setInventoryItems(prev => prev.map(item => item.id === id ? { ...item, ...updates } : item));
  };

  const deleteInventoryItem = (id: string) => {
    setInventoryItems(prev => prev.filter(item => item.id !== id));
  };

  const processInventoryTransaction = (txn: Omit<InventoryTransaction, "id" | "date" | "itemName">) => {
    const item = inventoryItems.find(i => i.id === txn.itemId);
    if (!item) return;

    if (txn.type === "issue" && item.quantity < txn.quantity) throw new Error("Insufficient stock");

    const newTxn: InventoryTransaction = {
      ...txn, id: `TRX-${Math.floor(1000 + Math.random() * 9000)}`, itemName: item.name, date: new Date().toISOString().split("T")[0],
    };

    setInventoryTransactions(prev => [newTxn, ...prev]);
    setInventoryItems(prev => prev.map(i => {
      if (i.id === txn.itemId) {
        const newQuantity = txn.type === "receive" ? i.quantity + txn.quantity : i.quantity - txn.quantity;
        const newStatus = newQuantity === 0 ? "out_of_stock" : newQuantity <= 10 ? "low_stock" : "available";
        return { ...i, quantity: newQuantity, status: newStatus };
      }
      return i;
    }));
  };

  const addStaff = (staffData: Omit<Staff, "id">) => {
    const existingStaff = staff.find(s => s.employeeNo && s.employeeNo === staffData.employeeNo);
    const newStaffId = existingStaff ? existingStaff.id : `EMP-${Math.floor(1000 + Math.random() * 9000)}`;

    if (!existingStaff) {
      const newStaff = { ...staffData, id: newStaffId } as Staff;
      setStaff(prev => [newStaff, ...prev]);
    }

    const newAssignment: EmployeeAssignment = {
      id: `EA-${Math.floor(1000 + Math.random() * 9000)}`,
      employeeId: newStaffId,
      academicYearId: currentAcademicYearId || "",
      stage: staffData.stage,
      role: staffData.role,
      department: staffData.department,
      status: staffData.status,
      basicSalary: staffData.basicSalary,
      allowance: staffData.allowance,
      deduction: staffData.deduction,
      paymentType: staffData.paymentType,
      rate: staffData.rate,
      subjects: staffData.subjects,
      sections: staffData.sections
    };
    setEmployeeAssignments(prev => [newAssignment, ...prev]);
  };

  const upsertStaffAttendance = (record: StaffAttendanceRecord) => {
    setStaffAttendance(prev => {
      const existing = prev.findIndex(r => r.staffId === record.staffId && r.date === record.date);
      if (existing >= 0) {
        const next = [...prev];
        next[existing] = record;
        return next;
      }
      return [...prev, record];
    });
  };

  const addStaffAdvance = (advanceData: Omit<StaffAdvance, "id">) => {
    setStaffAdvances(prev => [{ ...advanceData, id: `ADV-${Math.floor(1000 + Math.random() * 9000)}` }, ...prev]);
  };

  const updateStaff = (id: string, updates: Partial<Staff>) => {
    setStaff(prev => prev.map(s => s.id === id ? { ...s, ...updates } : s));
    setEmployeeAssignments(prev => prev.map(a => (a.employeeId === id && a.academicYearId === currentAcademicYearId) ? { ...a, ...updates } as EmployeeAssignment : a));
  };

  const softDeleteStaff = (id: string) => {
    setStaff(prev => prev.map(s => s.id === id ? { ...s, isDeleted: true, deletedAt: new Date().toISOString() } : s));
  };

  const restoreStaff = (id: string) => {
    setStaff(prev => prev.map(s => s.id === id ? { ...s, isDeleted: false, deletedAt: undefined } : s));
  };

  const hardDeleteStaff = (id: string) => {
    setStaff(prev => prev.filter(s => s.id !== id));
    setEmployeeAssignments(prev => prev.filter(a => a.employeeId !== id));
  };

  const restoreItem = (type: 'student' | 'guardian' | 'staff', id: string) => {
    if (type === 'student') restoreStudent(id);
    else if (type === 'staff') restoreStaff(id);
    else restoreGuardian(id);
  };

  const hardDeleteItem = (type: 'student' | 'guardian' | 'staff', id: string) => {
    if (type === 'student') hardDeleteStudent(id);
    else if (type === 'staff') hardDeleteStaff(id);
    else hardDeleteGuardian(id);
  };

  const addClinicVisit = (visitData: Omit<ClinicVisit, "id" | "studentName" | "stage">) => {
    const student = students.find(s => s.id === visitData.studentId);
    if (!student) return;

    const newVisit: ClinicVisit = {
      ...visitData,
      id: `CV-${Math.floor(1000 + Math.random() * 9000)}`,
      studentName: student.name,
      stage: student.stage,
    };
    setClinicVisits(prev => [newVisit, ...prev]);
  };

  const addDisciplineIncident = (incidentData: Omit<DisciplineIncident, "id">) => {
    const newIncident: DisciplineIncident = {
      ...incidentData,
      id: `DI-${Math.floor(1000 + Math.random() * 9000)}`,
    };
    setDisciplineIncidents(prev => [newIncident, ...prev]);
  };

  const addAttendanceSession = (sessionData: Omit<AttendanceSession, "id">, recordsData: Omit<AttendanceRecord, "id" | "sessionId">[]) => {
    const sessionId = `AS-${Math.floor(1000 + Math.random() * 9000)}`;
    const newSession: AttendanceSession = { ...sessionData, id: sessionId };
    
    const newRecords = recordsData.map(r => ({
      ...r,
      id: `AR-${Math.floor(10000 + Math.random() * 90000)}`,
      sessionId
    }));

    setAttendanceSessions(prev => [newSession, ...prev]);
    setAttendanceRecords(prev => [...newRecords, ...prev]);

    // Automatically generate warnings/incidents for absent students
    recordsData.forEach(r => {
      if (r.status === "ABSENT") {
        setDisciplineIncidents(prev => [{
          id: `DI-${Math.floor(1000 + Math.random() * 9000)}`,
          studentEnrollmentId: r.studentEnrollmentId,
          date: sessionData.date,
          description: `غياب غير مبرر عن الحصة ${sessionData.periodNumber || "اليوم"}`,
          responsiblePerson: "نظام الرصد التلقائي",
          actionTaken: "إنذار غياب مبدئي"
        }, ...prev]);
      }
    });
  };

  const addBehaviorTransaction = (transactionData: Omit<BehaviorTransaction, "id">) => {
    const newTransaction: BehaviorTransaction = {
      ...transactionData,
      id: `BTX-${Math.floor(1000 + Math.random() * 9000)}`,
    };
    setBehaviorTransactions(prev => [newTransaction, ...prev]);
  };

  const addSection = (sectionData: Omit<Section, "id">) => {
    setSections(prev => [{ ...sectionData, id: `SEC-${Math.floor(1000 + Math.random() * 9000)}` }, ...prev]);
  };

  const updateSection = (id: string, updates: Partial<Section>) => {
    setSections(prev => prev.map(s => s.id === id ? { ...s, ...updates } : s));
  };

  const deleteSection = (id: string) => {
    setSections(prev => prev.filter(s => s.id !== id));
  };

  const addExam = (examData: Omit<Exam, "id">) => {
    setExams(prev => [{ ...examData, id: `EX-${Math.floor(1000 + Math.random() * 9000)}` }, ...prev]);
  };

  const updateExam = (id: string, updates: Partial<Exam>) => {
    setExams(prev => prev.map(e => e.id === id ? { ...e, ...updates } : e));
  };

  const deleteExam = (id: string) => {
    setExams(prev => prev.filter(e => e.id !== id));
    // optionally cascade delete subjects and results...
  };

  const addExamSubject = (examSubject: Omit<ExamSubject, "id">) => {
    setExamSubjects(prev => [{ ...examSubject, id: `ES-${Math.floor(1000 + Math.random() * 9000)}` }, ...prev]);
  };

  const updateExamSubject = (id: string, updates: Partial<ExamSubject>) => {
    setExamSubjects(prev => prev.map(s => s.id === id ? { ...s, ...updates } : s));
  };

  const deleteExamSubject = (id: string) => {
    setExamSubjects(prev => prev.filter(s => s.id !== id));
  };

  const saveExamResults = (newResults: Omit<ExamResult, "id">[]) => {
    setExamResults(prev => {
      let updated = [...prev];
      for (const r of newResults) {
        const existingIdx = updated.findIndex(exr => exr.examSubjectId === r.examSubjectId && exr.studentEnrollmentId === r.studentEnrollmentId);
        if (existingIdx >= 0) {
          updated[existingIdx] = { ...updated[existingIdx], mark: r.mark, notes: r.notes, status: r.status };
        } else {
          updated.push({ ...r, id: `ER-${Math.floor(1000 + Math.random() * 9000)}` });
        }
      }
      return updated;
    });
  };

  const addSubject = (subjectData: Omit<Subject, "id">) => {
    setSubjects(prev => [{ ...subjectData, id: `SUB-${Math.floor(1000 + Math.random() * 9000)}` }, ...prev]);
  };

  const deleteSubject = (id: string) => {
    setSubjects(prev => prev.filter(s => s.id !== id));
  };

  const updateScheduleSlot = (slotData: Omit<ScheduleSlot, "id">) => {
    setScheduleSlots(prev => {
      const existingIdx = prev.findIndex(s => s.sectionId === slotData.sectionId && s.day === slotData.day && s.period === slotData.period);
      if (existingIdx >= 0) {
        let updated = [...prev];
        updated[existingIdx] = { ...updated[existingIdx], ...slotData };
        return updated;
      } else {
        return [...prev, { ...slotData, id: `SCH-${Math.floor(1000 + Math.random() * 9000)}` }];
      }
    });
  };

  const clearScheduleSlot = (sectionId: string, day: string, period: number) => {
    setScheduleSlots(prev => prev.filter(s => !(s.sectionId === sectionId && s.day === day && s.period === period)));
  };

  const addAcademicYear = (yearData: Omit<AcademicYear, "id">) => {
    setAcademicYears(prev => {
      let newState = [...prev];
      if (yearData.isCurrent) {
        newState = newState.map(y => ({ ...y, isCurrent: false }));
      }
      newState.push({ ...yearData, id: `Y-${Math.floor(1000 + Math.random() * 9000)}` });
      return newState;
    });
  };

  const updateAcademicYear = (id: string, updates: Partial<AcademicYear>) => {
    setAcademicYears(prev => {
      let newState = [...prev];
      if (updates.isCurrent) {
        newState = newState.map(y => ({ ...y, isCurrent: false }));
      }
      newState = newState.map(y => y.id === id ? { ...y, ...updates } : y);
      return newState;
    });
  };

  const addTeachingAssignment = (assignmentData: Omit<TeachingAssignment, "id">) => {
    setTeachingAssignments(prev => [{ ...assignmentData, id: `TA-${Math.floor(1000 + Math.random() * 9000)}` }, ...prev]);
  };

  const deleteTeachingAssignment = (id: string) => {
    setTeachingAssignments(prev => prev.filter(a => a.id !== id));
  };

  const addMaintenanceRequest = (req: Omit<MaintenanceRequest, "id">) => {
    setMaintenanceRequests(prev => [{ ...req, id: `MR-${Math.floor(1000 + Math.random() * 9000)}` }, ...prev]);
  };
  const updateMaintenanceRequest = (id: string, updates: Partial<MaintenanceRequest>) => {
    setMaintenanceRequests(prev => prev.map(r => {
      if (r.id === id) {
        const updated = { ...r, ...updates };
        if (updates.status === "completed" && r.status !== "completed" && updated.costEstimate) {
          // create expense when maintenance completed
          addExpense({
            title: `صيانة: ${updated.title}`,
            amount: updated.costEstimate,
            date: new Date().toISOString().split("T")[0],
            categoryId: "EXPCAT-4", // Maintenance category
            beneficiary: "مقاول صيانة",
            method: "bank_transfer"
          });
        }
        return updated;
      }
      return r;
    }));
  };
  const undoMaintenanceRequest = (id: string) => setMaintenanceRequests(prev => prev.map(r => r.id === id ? { ...r, status: "new" } : r));
  const deleteMaintenanceRequest = (id: string) => {
    setMaintenanceRequests(prev => prev.filter(r => r.id !== id));
  };

  const addRoom = (room: Omit<Room, "id">) => setRooms(prev => [{ ...room, id: `RM-${Math.floor(1000 + Math.random() * 9000)}` }, ...prev]);
  const updateRoom = (id: string, updates: Partial<Room>) => setRooms(prev => prev.map(r => r.id === id ? { ...r, ...updates } : r));
  const deleteRoom = (id: string) => setRooms(prev => prev.filter(r => r.id !== id));

  const addStaffEvaluation = (evalData: Omit<StaffEvaluation, "id">) => setStaffEvaluations(prev => [{ ...evalData, id: `SE-${Math.floor(1000 + Math.random() * 9000)}` }, ...prev]);
  const addStaffContract = (contractData: Omit<StaffContract, "id">) => setStaffContracts(prev => [{ ...contractData, id: `SC-${Math.floor(1000 + Math.random() * 9000)}` }, ...prev]);
  
  const addStaffLeave = (leaveData: Omit<StaffLeave, "id">) => setStaffLeaves(prev => [{ ...leaveData, id: `SL-${Math.floor(1000 + Math.random() * 9000)}` }, ...prev]);
  const updateStaffLeave = (id: string, updates: Partial<StaffLeave>) => setStaffLeaves(prev => prev.map(l => l.id === id ? { ...l, ...updates } : l));

  const addActivityLog = (logData: Omit<ActivityLog, "id" | "date">) => {
    setActivityLogs(prev => [{ ...logData, id: `AL-${Math.floor(1000 + Math.random() * 9000)}`, date: new Date().toISOString() }, ...prev]);
  };

  const addUser = (userData: Omit<UserAccount, "id">) => {
    const newUser: UserAccount = { ...userData, id: `U-${Math.floor(1000 + Math.random() * 9000)}` };
    setUsers(prev => [newUser, ...prev]);
    addActivityLog({ user: "مدير النظام", action: "إضافة مستخدم", entity: "المستخدمون", details: `تم إنشاء حساب: ${userData.fullName} (${userData.username})` });
  };

  const updateUser = (id: string, updates: Partial<UserAccount>) => {
    setUsers(prev => prev.map(u => u.id === id ? { ...u, ...updates } : u));
    const user = users.find(u => u.id === id);
    addActivityLog({ user: "مدير النظام", action: "تعديل مستخدم", entity: "المستخدمون", details: `تم تعديل حساب: ${user?.fullName || id}` });
  };

  const deleteUser = (id: string) => {
    const user = users.find(u => u.id === id);
    setUsers(prev => prev.filter(u => u.id !== id));
    addActivityLog({ user: "مدير النظام", action: "حذف مستخدم", entity: "المستخدمون", details: `تم حذف حساب: ${user?.fullName || id}` });
  };

  const generateBulkData = (count: number) => {
    const stages: EducationalStage[] = ["kindergarten", "primary", "middle", "high"];
    const names = ["أحمد", "محمد", "علي", "سارة", "فاطمة", "خالد", "عبدالله", "عمر", "نورة", "مريم", "سعد", "فيصل", "نوف", "هند", "عبير"];
    const family = ["العتيبي", "القحطاني", "الشمري", "الدوسري", "الزهراني", "المطيري", "الغامدي", "العنزي", "الشهري", "السبيعي"];
    const grades = ["الصف الأول", "الصف الثاني", "الصف الثالث", "الصف الرابع", "الصف الخامس", "الصف السادس", "مستوى أول", "مستوى ثاني"];

    const newStudents: Student[] = [];
    const newInvoices: Invoice[] = [];
    const newClinicVisits: ClinicVisit[] = [];
    const newDisciplineIncidents: DisciplineIncident[] = [];
    const newLibraryIssues: LibraryIssue[] = [];

    // Optimize DOM freeze by using Date.now once
    const now = Date.now();

    for (let i = 0; i < count; i++) {
      const stage = stages[Math.floor(Math.random() * stages.length)];
      const name = `${names[Math.floor(Math.random() * names.length)]} ${names[Math.floor(Math.random() * names.length)]} ${family[Math.floor(Math.random() * family.length)]}`;
      const id = `STU-BLK-${i}-${now}`;
      
      newStudents.push({
        id,
        name,
        dob: "2010-01-01",
        nationalId: `1${Math.floor(Math.random() * 900000000)}`,
        guardianName: `والد ${name}`,
        stage,
        grade: grades[Math.floor(Math.random() * grades.length)],
        status: "نشط",
        gender: Math.random() > 0.5 ? "ذكر" : "أنثى"
      });

      const isPaid = Math.random() > 0.5;
      newInvoices.push({
        id: `INV-BLK-${i}-${now}`,
        studentId: id,
        studentName: name,
        amount: 5000,
        paid: isPaid ? 5000 : 0,
        dueDate: "2024-01-01",
        status: isPaid ? "paid" : "issued",
        stage
      });

      if (Math.random() > 0.95) {
        newClinicVisits.push({
           id: `CV-BLK-${i}-${now}`,
           studentId: id,
           studentName: name,
           date: new Date().toISOString().split("T")[0],
           symptoms: "صداع",
           diagnosis: "إرهاق",
           actionTaken: "إعطاء مسكن",
           stage
        });
      }



      if (Math.random() > 0.98) {
        newLibraryIssues.push({
          id: `IS-BLK-${i}-${now}`,
          bookId: "B-1001",
          bookTitle: "كتاب الإعارة التلقائي",
          studentId: id,
          studentName: name,
          issueDate: new Date().toISOString().split("T")[0],
          dueDate: new Date().toISOString().split("T")[0],
          status: "active",
          stage
        });
      }
    }

    setStudents(prev => [...newStudents, ...prev]);
    setInvoices(prev => [...newInvoices, ...prev]);
    setClinicVisits(prev => [...newClinicVisits, ...prev]);
    setDisciplineIncidents(prev => [...newDisciplineIncidents, ...prev]);
    setLibraryIssues(prev => [...newLibraryIssues, ...prev]);
  };

  const addTextbook = (tb: Omit<Textbook, "id">) => setTextbooks(prev => [{ ...tb, id: `TB-${Math.floor(1000 + Math.random() * 9000)}` }, ...prev]);
  const updateTextbook = (id: string, updates: Partial<Textbook>) => setTextbooks(prev => prev.map(t => t.id === id ? { ...t, ...updates } : t));
  const deleteTextbook = (id: string) => setTextbooks(prev => prev.filter(t => t.id !== id));
  const distributeTextbook = (distribution: Omit<TextbookDistribution, "id" | "date" | "status">) => {
    setTextbookDistributions(prev => [{
      id: `TBD-${Math.floor(1000 + Math.random() * 9000)}`,
      ...distribution,
      date: new Date().toISOString().split('T')[0],
      status: "distributed",
    }, ...prev]);
  };
  const removeDistribution = (id: string) => setTextbookDistributions(prev => prev.filter(d => d.id !== id));

  const addTransportRoute = (r: Omit<TransportRoute, "id">) => setTransportRoutes(prev => [{ ...r, id: `RT-${Math.floor(1000 + Math.random() * 9000)}` }, ...prev]);
  const updateTransportRoute = (id: string, updates: Partial<TransportRoute>) => setTransportRoutes(prev => prev.map(r => r.id === id ? { ...r, ...updates } : r));
  const deleteTransportRoute = (id: string) => setTransportRoutes(prev => prev.filter(r => r.id !== id));

  const addTransportSubscription = (s: Omit<TransportSubscription, "id">) => setTransportSubscriptions(prev => [{ ...s, id: `SUB-${Math.floor(1000 + Math.random() * 9000)}` }, ...prev]);
  const updateTransportSubscription = (id: string, updates: Partial<TransportSubscription>) => setTransportSubscriptions(prev => prev.map(s => s.id === id ? { ...s, ...updates } : s));
  const deleteTransportSubscription = (id: string) => setTransportSubscriptions(prev => prev.filter(s => s.id !== id));

  const updateTimetableSettings = (updates: Partial<TimetableSettings>) => setTimetableSettings(prev => ({ ...prev, ...updates }));

  return (
    <GlobalStoreContext.Provider value={{
      allStudents: students,
      allDeletedStudents,
      allStudentEnrollments: studentEnrollments,
      allEmployeeAssignments: employeeAssignments,
      allInvoices: invoices, allFeeStructures: feeStructures, allDiscounts: discounts, allPayments: payments, allExpenses: expenses,
      allExpenseCategories: expenseCategories,
      allAccounts: accounts,
      allJournalEntries: journalEntries,
      allJournalLines: journalLines,
      allAuditLogs: auditLogs,
      allBooks: books, allLibraryIssues: libraryIssues,
      allInventoryItems: inventoryItems, allInventoryTransactions: inventoryTransactions,
      allStaff: staff, allClinicVisits: clinicVisits, allDisciplineIncidents: disciplineIncidents,
      allSections: sections, allExams: exams, allExamSubjects: examSubjects, allExamResults: examResults, allSubjects: subjects,
      allScheduleSlots: scheduleSlots, allAcademicYears: academicYears, allTeachingAssignments: teachingAssignments,
      
      allMaintenanceRequests: maintenanceRequests, allRooms: rooms,
      allStaffEvaluations: staffEvaluations, allStaffContracts: staffContracts, allStaffLeaves: staffLeaves,
      allStaffAttendance: staffAttendance, allStaffAdvances: staffAdvances,
      allActivityLogs: activityLogs,
      allUsers: users,
      allAttendanceSessions: attendanceSessions,
      allAttendanceRecords: attendanceRecords,
      allAttendanceExcuses: attendanceExcuses,
      allBehaviorTransactions: behaviorTransactions,
      allDisciplineCategories: disciplineCategories,
      allDisciplineActions: disciplineActions,

      activeStageStudents, activeStageInvoices, activeStageFeeStructures, activeStageBooks, activeStageLibraryIssues,
      activeStageStaff, activeStageStaffAttendance, activeStageClinicVisits, activeStageDisciplineIncidents, activeStageSections,
      activeStageExams, activeStageExamSubjects, activeStageSubjects,
      activeStageScheduleSlots, activeStageTeachingAssignments,
      allGuardians: guardians,
      
      allTextbooks: textbooks,
      allTextbookDistributions: textbookDistributions,
      activeStageTextbooks,
      activeStageDistributions,
      addTextbook,
      updateTextbook,
      deleteTextbook,
      distributeTextbook,
      removeDistribution,
      transportRoutes,
      transportSubscriptions,
      addTransportRoute,
      updateTransportRoute,
      deleteTransportRoute,
      addTransportSubscription,
      updateTransportSubscription,
      deleteTransportSubscription,
      activeStageTimetableSettings,
      updateTimetableSettings,
      systemSettings,
      updateSettings,
      
      addStudent,
      updateStudent,
      softDeleteStudent,
      restoreStudent,
      hardDeleteStudent,
      addGuardian, updateGuardian, softDeleteGuardian, restoreGuardian, hardDeleteGuardian,
      restoreItem, hardDeleteItem,
      addPayment, addInvoice, issueInvoice, cancelInvoice, updateInvoice, deleteInvoice, addFeeStructure, updateFeeStructure, deleteFeeStructure, addDiscount, updateDiscount, deleteDiscount, addExpense, submitExpense, approveExpense, postExpense, updateExpense, deleteExpense, addJournalEntry, rolloverFinancialBalances,
      addAccount, updateAccount, deleteAccount, toggleAccountStatus,
      addBook, issueBook, returnBook, addInventoryItem, updateInventoryItem, deleteInventoryItem,
      processInventoryTransaction, addStaff, updateStaff, deleteStaff: hardDeleteStaff, upsertStaffAttendance, addStaffAdvance, addClinicVisit, addDisciplineIncident, addAttendanceSession, addBehaviorTransaction,
      addSection, updateSection, deleteSection, 

      currency,
      setCurrency,
      addExam, updateExam, deleteExam, addExamSubject, updateExamSubject, deleteExamSubject, saveExamResults, addSubject, deleteSubject,
      updateScheduleSlot, clearScheduleSlot, addAcademicYear, updateAcademicYear, addTeachingAssignment, deleteTeachingAssignment,
      assignStudentToSection,
      promoteStudents,
      promoteStaff,
      
      addMaintenanceRequest, updateMaintenanceRequest, undoMaintenanceRequest, deleteMaintenanceRequest,
      addRoom, updateRoom, deleteRoom,
      addStaffEvaluation, addStaffContract, addStaffLeave, updateStaffLeave,
      addActivityLog,
      addUser, updateUser, deleteUser,

      generateBulkData,

      notifications,
      unreadNotificationsCount,
      markAllNotificationsAsRead,
      deleteNotification,
      addNotification,
      currentAcademicYearId
    }}>
      {children}
    </GlobalStoreContext.Provider>
  );
}

export function useGlobalStore() {
  const context = useContext(GlobalStoreContext);
  if (context === undefined) throw new Error("useGlobalStore must be used within a GlobalStoreProvider");
  return context;
}
