/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HrRouteImport } from './routes/hr'
import { Route as GuardiansRouteImport } from './routes/guardians'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as DisciplineRouteImport } from './routes/discipline'
import { Route as ClinicRouteImport } from './routes/clinic'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcademicRouteImport } from './routes/academic'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeachersIndexRouteImport } from './routes/teachers.index'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as GuardiansIndexRouteImport } from './routes/guardians.index'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as ExamsIndexRouteImport } from './routes/exams.index'
import { Route as TransportStudentsRouteImport } from './routes/transport.students'
import { Route as TransportRoutesRouteImport } from './routes/transport.routes'
import { Route as TeachersIdRouteImport } from './routes/teachers.$id'
import { Route as StudentsNewRouteImport } from './routes/students.new'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as SettingsTrashRouteImport } from './routes/settings.trash'
import { Route as LibraryTextbooksRouteImport } from './routes/library.textbooks'
import { Route as LibraryDistributionRouteImport } from './routes/library.distribution'
import { Route as InventoryItemsRouteImport } from './routes/inventory.items'
import { Route as HrReportsRouteImport } from './routes/hr.reports'
import { Route as HrPayrollRouteImport } from './routes/hr.payroll'
import { Route as HrOrgChartRouteImport } from './routes/hr.org-chart'
import { Route as HrLeavesRouteImport } from './routes/hr.leaves'
import { Route as HrEvaluationsRouteImport } from './routes/hr.evaluations'
import { Route as HrDashboardRouteImport } from './routes/hr.dashboard'
import { Route as HrContractsRouteImport } from './routes/hr.contracts'
import { Route as HrAttendanceRouteImport } from './routes/hr.attendance'
import { Route as GuardiansIdRouteImport } from './routes/guardians.$id'
import { Route as FinanceVendorsRouteImport } from './routes/finance.vendors'
import { Route as FinanceTrialBalanceRouteImport } from './routes/finance.trial-balance'
import { Route as FinanceTreasuryRouteImport } from './routes/finance.treasury'
import { Route as FinanceStudentsRouteImport } from './routes/finance.students'
import { Route as FinanceReportsRouteImport } from './routes/finance.reports'
import { Route as FinancePaymentsRouteImport } from './routes/finance.payments'
import { Route as FinanceLedgerRouteImport } from './routes/finance.ledger'
import { Route as FinanceFeesRouteImport } from './routes/finance.fees'
import { Route as FinanceExpensesRouteImport } from './routes/finance.expenses'
import { Route as FinanceDiscountsRouteImport } from './routes/finance.discounts'
import { Route as FinanceDashboardRouteImport } from './routes/finance.dashboard'
import { Route as FinanceCostCentersRouteImport } from './routes/finance.cost-centers'
import { Route as FinanceBudgetsRouteImport } from './routes/finance.budgets'
import { Route as FinanceBanksRouteImport } from './routes/finance.banks'
import { Route as FinanceAdvancedRouteImport } from './routes/finance.advanced'
import { Route as FinanceAccountsRouteImport } from './routes/finance.accounts'
import { Route as FacilitiesRoomsRouteImport } from './routes/facilities.rooms'
import { Route as FacilitiesMaintenanceRouteImport } from './routes/facilities.maintenance'
import { Route as FacilitiesDashboardRouteImport } from './routes/facilities.dashboard'
import { Route as ExamsReportsRouteImport } from './routes/exams.reports'
import { Route as ExamsGradesRouteImport } from './routes/exams.grades'
import { Route as DisciplineMeritsRouteImport } from './routes/discipline.merits'
import { Route as DisciplineIncidentsRouteImport } from './routes/discipline.incidents'
import { Route as ClinicVisitsRouteImport } from './routes/clinic.visits'
import { Route as AttendanceTakeRouteImport } from './routes/attendance.take'
import { Route as AttendanceReportsRouteImport } from './routes/attendance.reports'
import { Route as AdmissionsIdRouteImport } from './routes/admissions.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminBackupRouteImport } from './routes/admin.backup'
import { Route as AdminActivityLogRouteImport } from './routes/admin.activity-log'
import { Route as AcademicYearsRouteImport } from './routes/academic.years'
import { Route as AcademicSubjectsRouteImport } from './routes/academic.subjects'
import { Route as AcademicClassesRouteImport } from './routes/academic.classes'
import { Route as AcademicAssignmentsRouteImport } from './routes/academic.assignments'
import { Route as HrStaffIndexRouteImport } from './routes/hr.staff.index'
import { Route as HrStaffIdRouteImport } from './routes/hr.staff.$id'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardiansRoute = GuardiansRouteImport.update({
  id: '/guardians',
  path: '/guardians',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplineRoute = DisciplineRouteImport.update({
  id: '/discipline',
  path: '/discipline',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicRoute = ClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicRoute = AcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersIndexRoute = TeachersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeachersRoute,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentsRoute,
} as any)
const GuardiansIndexRoute = GuardiansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuardiansRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const ExamsIndexRoute = ExamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamsRoute,
} as any)
const TransportStudentsRoute = TransportStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TransportRoute,
} as any)
const TransportRoutesRoute = TransportRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => TransportRoute,
} as any)
const TeachersIdRoute = TeachersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeachersRoute,
} as any)
const StudentsNewRoute = StudentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StudentsRoute,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentsRoute,
} as any)
const SettingsTrashRoute = SettingsTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => SettingsRoute,
} as any)
const LibraryTextbooksRoute = LibraryTextbooksRouteImport.update({
  id: '/textbooks',
  path: '/textbooks',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryDistributionRoute = LibraryDistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => LibraryRoute,
} as any)
const InventoryItemsRoute = InventoryItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => InventoryRoute,
} as any)
const HrReportsRoute = HrReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => HrRoute,
} as any)
const HrPayrollRoute = HrPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => HrRoute,
} as any)
const HrOrgChartRoute = HrOrgChartRouteImport.update({
  id: '/org-chart',
  path: '/org-chart',
  getParentRoute: () => HrRoute,
} as any)
const HrLeavesRoute = HrLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => HrRoute,
} as any)
const HrEvaluationsRoute = HrEvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => HrRoute,
} as any)
const HrDashboardRoute = HrDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HrRoute,
} as any)
const HrContractsRoute = HrContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => HrRoute,
} as any)
const HrAttendanceRoute = HrAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => HrRoute,
} as any)
const GuardiansIdRoute = GuardiansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GuardiansRoute,
} as any)
const FinanceVendorsRoute = FinanceVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceTrialBalanceRoute = FinanceTrialBalanceRouteImport.update({
  id: '/trial-balance',
  path: '/trial-balance',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceTreasuryRoute = FinanceTreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceStudentsRoute = FinanceStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceReportsRoute = FinanceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => FinanceRoute,
} as any)
const FinancePaymentsRoute = FinancePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceLedgerRoute = FinanceLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceFeesRoute = FinanceFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceExpensesRoute = FinanceExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceDiscountsRoute = FinanceDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceDashboardRoute = FinanceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceCostCentersRoute = FinanceCostCentersRouteImport.update({
  id: '/cost-centers',
  path: '/cost-centers',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceBudgetsRoute = FinanceBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceBanksRoute = FinanceBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceAdvancedRoute = FinanceAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceAccountsRoute = FinanceAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => FinanceRoute,
} as any)
const FacilitiesRoomsRoute = FacilitiesRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => FacilitiesRoute,
} as any)
const FacilitiesMaintenanceRoute = FacilitiesMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => FacilitiesRoute,
} as any)
const FacilitiesDashboardRoute = FacilitiesDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => FacilitiesRoute,
} as any)
const ExamsReportsRoute = ExamsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ExamsRoute,
} as any)
const ExamsGradesRoute = ExamsGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => ExamsRoute,
} as any)
const DisciplineMeritsRoute = DisciplineMeritsRouteImport.update({
  id: '/merits',
  path: '/merits',
  getParentRoute: () => DisciplineRoute,
} as any)
const DisciplineIncidentsRoute = DisciplineIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => DisciplineRoute,
} as any)
const ClinicVisitsRoute = ClinicVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => ClinicRoute,
} as any)
const AttendanceTakeRoute = AttendanceTakeRouteImport.update({
  id: '/take',
  path: '/take',
  getParentRoute: () => AttendanceRoute,
} as any)
const AttendanceReportsRoute = AttendanceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AttendanceRoute,
} as any)
const AdmissionsIdRoute = AdmissionsIdRouteImport.update({
  id: '/admissions/$id',
  path: '/admissions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupRoute = AdminBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityLogRoute = AdminActivityLogRouteImport.update({
  id: '/activity-log',
  path: '/activity-log',
  getParentRoute: () => AdminRoute,
} as any)
const AcademicYearsRoute = AcademicYearsRouteImport.update({
  id: '/years',
  path: '/years',
  getParentRoute: () => AcademicRoute,
} as any)
const AcademicSubjectsRoute = AcademicSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AcademicRoute,
} as any)
const AcademicClassesRoute = AcademicClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AcademicRoute,
} as any)
const AcademicAssignmentsRoute = AcademicAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AcademicRoute,
} as any)
const HrStaffIndexRoute = HrStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => HrRoute,
} as any)
const HrStaffIdRoute = HrStaffIdRouteImport.update({
  id: '/staff/$id',
  path: '/staff/$id',
  getParentRoute: () => HrRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academic': typeof AcademicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/attendance': typeof AttendanceRouteWithChildren
  '/clinic': typeof ClinicRouteWithChildren
  '/discipline': typeof DisciplineRouteWithChildren
  '/exams': typeof ExamsRouteWithChildren
  '/facilities': typeof FacilitiesRouteWithChildren
  '/finance': typeof FinanceRouteWithChildren
  '/guardians': typeof GuardiansRouteWithChildren
  '/hr': typeof HrRouteWithChildren
  '/inventory': typeof InventoryRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRouteWithChildren
  '/students': typeof StudentsRouteWithChildren
  '/teachers': typeof TeachersRouteWithChildren
  '/transport': typeof TransportRouteWithChildren
  '/academic/assignments': typeof AcademicAssignmentsRoute
  '/academic/classes': typeof AcademicClassesRoute
  '/academic/subjects': typeof AcademicSubjectsRoute
  '/academic/years': typeof AcademicYearsRoute
  '/admin/activity-log': typeof AdminActivityLogRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admissions/$id': typeof AdmissionsIdRoute
  '/attendance/reports': typeof AttendanceReportsRoute
  '/attendance/take': typeof AttendanceTakeRoute
  '/clinic/visits': typeof ClinicVisitsRoute
  '/discipline/incidents': typeof DisciplineIncidentsRoute
  '/discipline/merits': typeof DisciplineMeritsRoute
  '/exams/grades': typeof ExamsGradesRoute
  '/exams/reports': typeof ExamsReportsRoute
  '/facilities/dashboard': typeof FacilitiesDashboardRoute
  '/facilities/maintenance': typeof FacilitiesMaintenanceRoute
  '/facilities/rooms': typeof FacilitiesRoomsRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/advanced': typeof FinanceAdvancedRoute
  '/finance/banks': typeof FinanceBanksRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/cost-centers': typeof FinanceCostCentersRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/discounts': typeof FinanceDiscountsRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/fees': typeof FinanceFeesRoute
  '/finance/ledger': typeof FinanceLedgerRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/finance/students': typeof FinanceStudentsRoute
  '/finance/treasury': typeof FinanceTreasuryRoute
  '/finance/trial-balance': typeof FinanceTrialBalanceRoute
  '/finance/vendors': typeof FinanceVendorsRoute
  '/guardians/$id': typeof GuardiansIdRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/contracts': typeof HrContractsRoute
  '/hr/dashboard': typeof HrDashboardRoute
  '/hr/evaluations': typeof HrEvaluationsRoute
  '/hr/leaves': typeof HrLeavesRoute
  '/hr/org-chart': typeof HrOrgChartRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/reports': typeof HrReportsRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/library/distribution': typeof LibraryDistributionRoute
  '/library/textbooks': typeof LibraryTextbooksRoute
  '/settings/trash': typeof SettingsTrashRoute
  '/students/$id': typeof StudentsIdRoute
  '/students/new': typeof StudentsNewRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/transport/routes': typeof TransportRoutesRoute
  '/transport/students': typeof TransportStudentsRoute
  '/exams/': typeof ExamsIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/guardians/': typeof GuardiansIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/hr/staff/$id': typeof HrStaffIdRoute
  '/hr/staff/': typeof HrStaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academic': typeof AcademicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/attendance': typeof AttendanceRouteWithChildren
  '/clinic': typeof ClinicRouteWithChildren
  '/discipline': typeof DisciplineRouteWithChildren
  '/facilities': typeof FacilitiesRouteWithChildren
  '/hr': typeof HrRouteWithChildren
  '/inventory': typeof InventoryRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRouteWithChildren
  '/transport': typeof TransportRouteWithChildren
  '/academic/assignments': typeof AcademicAssignmentsRoute
  '/academic/classes': typeof AcademicClassesRoute
  '/academic/subjects': typeof AcademicSubjectsRoute
  '/academic/years': typeof AcademicYearsRoute
  '/admin/activity-log': typeof AdminActivityLogRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admissions/$id': typeof AdmissionsIdRoute
  '/attendance/reports': typeof AttendanceReportsRoute
  '/attendance/take': typeof AttendanceTakeRoute
  '/clinic/visits': typeof ClinicVisitsRoute
  '/discipline/incidents': typeof DisciplineIncidentsRoute
  '/discipline/merits': typeof DisciplineMeritsRoute
  '/exams/grades': typeof ExamsGradesRoute
  '/exams/reports': typeof ExamsReportsRoute
  '/facilities/dashboard': typeof FacilitiesDashboardRoute
  '/facilities/maintenance': typeof FacilitiesMaintenanceRoute
  '/facilities/rooms': typeof FacilitiesRoomsRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/advanced': typeof FinanceAdvancedRoute
  '/finance/banks': typeof FinanceBanksRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/cost-centers': typeof FinanceCostCentersRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/discounts': typeof FinanceDiscountsRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/fees': typeof FinanceFeesRoute
  '/finance/ledger': typeof FinanceLedgerRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/finance/students': typeof FinanceStudentsRoute
  '/finance/treasury': typeof FinanceTreasuryRoute
  '/finance/trial-balance': typeof FinanceTrialBalanceRoute
  '/finance/vendors': typeof FinanceVendorsRoute
  '/guardians/$id': typeof GuardiansIdRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/contracts': typeof HrContractsRoute
  '/hr/dashboard': typeof HrDashboardRoute
  '/hr/evaluations': typeof HrEvaluationsRoute
  '/hr/leaves': typeof HrLeavesRoute
  '/hr/org-chart': typeof HrOrgChartRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/reports': typeof HrReportsRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/library/distribution': typeof LibraryDistributionRoute
  '/library/textbooks': typeof LibraryTextbooksRoute
  '/settings/trash': typeof SettingsTrashRoute
  '/students/$id': typeof StudentsIdRoute
  '/students/new': typeof StudentsNewRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/transport/routes': typeof TransportRoutesRoute
  '/transport/students': typeof TransportStudentsRoute
  '/exams': typeof ExamsIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/guardians': typeof GuardiansIndexRoute
  '/students': typeof StudentsIndexRoute
  '/teachers': typeof TeachersIndexRoute
  '/hr/staff/$id': typeof HrStaffIdRoute
  '/hr/staff': typeof HrStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academic': typeof AcademicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/attendance': typeof AttendanceRouteWithChildren
  '/clinic': typeof ClinicRouteWithChildren
  '/discipline': typeof DisciplineRouteWithChildren
  '/exams': typeof ExamsRouteWithChildren
  '/facilities': typeof FacilitiesRouteWithChildren
  '/finance': typeof FinanceRouteWithChildren
  '/guardians': typeof GuardiansRouteWithChildren
  '/hr': typeof HrRouteWithChildren
  '/inventory': typeof InventoryRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRouteWithChildren
  '/students': typeof StudentsRouteWithChildren
  '/teachers': typeof TeachersRouteWithChildren
  '/transport': typeof TransportRouteWithChildren
  '/academic/assignments': typeof AcademicAssignmentsRoute
  '/academic/classes': typeof AcademicClassesRoute
  '/academic/subjects': typeof AcademicSubjectsRoute
  '/academic/years': typeof AcademicYearsRoute
  '/admin/activity-log': typeof AdminActivityLogRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admissions/$id': typeof AdmissionsIdRoute
  '/attendance/reports': typeof AttendanceReportsRoute
  '/attendance/take': typeof AttendanceTakeRoute
  '/clinic/visits': typeof ClinicVisitsRoute
  '/discipline/incidents': typeof DisciplineIncidentsRoute
  '/discipline/merits': typeof DisciplineMeritsRoute
  '/exams/grades': typeof ExamsGradesRoute
  '/exams/reports': typeof ExamsReportsRoute
  '/facilities/dashboard': typeof FacilitiesDashboardRoute
  '/facilities/maintenance': typeof FacilitiesMaintenanceRoute
  '/facilities/rooms': typeof FacilitiesRoomsRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/advanced': typeof FinanceAdvancedRoute
  '/finance/banks': typeof FinanceBanksRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/cost-centers': typeof FinanceCostCentersRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/discounts': typeof FinanceDiscountsRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/fees': typeof FinanceFeesRoute
  '/finance/ledger': typeof FinanceLedgerRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/finance/students': typeof FinanceStudentsRoute
  '/finance/treasury': typeof FinanceTreasuryRoute
  '/finance/trial-balance': typeof FinanceTrialBalanceRoute
  '/finance/vendors': typeof FinanceVendorsRoute
  '/guardians/$id': typeof GuardiansIdRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/contracts': typeof HrContractsRoute
  '/hr/dashboard': typeof HrDashboardRoute
  '/hr/evaluations': typeof HrEvaluationsRoute
  '/hr/leaves': typeof HrLeavesRoute
  '/hr/org-chart': typeof HrOrgChartRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/reports': typeof HrReportsRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/library/distribution': typeof LibraryDistributionRoute
  '/library/textbooks': typeof LibraryTextbooksRoute
  '/settings/trash': typeof SettingsTrashRoute
  '/students/$id': typeof StudentsIdRoute
  '/students/new': typeof StudentsNewRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/transport/routes': typeof TransportRoutesRoute
  '/transport/students': typeof TransportStudentsRoute
  '/exams/': typeof ExamsIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/guardians/': typeof GuardiansIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/hr/staff/$id': typeof HrStaffIdRoute
  '/hr/staff/': typeof HrStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic'
    | '/admin'
    | '/attendance'
    | '/clinic'
    | '/discipline'
    | '/exams'
    | '/facilities'
    | '/finance'
    | '/guardians'
    | '/hr'
    | '/inventory'
    | '/library'
    | '/profile'
    | '/schedule'
    | '/settings'
    | '/students'
    | '/teachers'
    | '/transport'
    | '/academic/assignments'
    | '/academic/classes'
    | '/academic/subjects'
    | '/academic/years'
    | '/admin/activity-log'
    | '/admin/backup'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/users'
    | '/admissions/$id'
    | '/attendance/reports'
    | '/attendance/take'
    | '/clinic/visits'
    | '/discipline/incidents'
    | '/discipline/merits'
    | '/exams/grades'
    | '/exams/reports'
    | '/facilities/dashboard'
    | '/facilities/maintenance'
    | '/facilities/rooms'
    | '/finance/accounts'
    | '/finance/advanced'
    | '/finance/banks'
    | '/finance/budgets'
    | '/finance/cost-centers'
    | '/finance/dashboard'
    | '/finance/discounts'
    | '/finance/expenses'
    | '/finance/fees'
    | '/finance/ledger'
    | '/finance/payments'
    | '/finance/reports'
    | '/finance/students'
    | '/finance/treasury'
    | '/finance/trial-balance'
    | '/finance/vendors'
    | '/guardians/$id'
    | '/hr/attendance'
    | '/hr/contracts'
    | '/hr/dashboard'
    | '/hr/evaluations'
    | '/hr/leaves'
    | '/hr/org-chart'
    | '/hr/payroll'
    | '/hr/reports'
    | '/inventory/items'
    | '/library/distribution'
    | '/library/textbooks'
    | '/settings/trash'
    | '/students/$id'
    | '/students/new'
    | '/teachers/$id'
    | '/transport/routes'
    | '/transport/students'
    | '/exams/'
    | '/finance/'
    | '/guardians/'
    | '/students/'
    | '/teachers/'
    | '/hr/staff/$id'
    | '/hr/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academic'
    | '/admin'
    | '/attendance'
    | '/clinic'
    | '/discipline'
    | '/facilities'
    | '/hr'
    | '/inventory'
    | '/library'
    | '/profile'
    | '/schedule'
    | '/settings'
    | '/transport'
    | '/academic/assignments'
    | '/academic/classes'
    | '/academic/subjects'
    | '/academic/years'
    | '/admin/activity-log'
    | '/admin/backup'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/users'
    | '/admissions/$id'
    | '/attendance/reports'
    | '/attendance/take'
    | '/clinic/visits'
    | '/discipline/incidents'
    | '/discipline/merits'
    | '/exams/grades'
    | '/exams/reports'
    | '/facilities/dashboard'
    | '/facilities/maintenance'
    | '/facilities/rooms'
    | '/finance/accounts'
    | '/finance/advanced'
    | '/finance/banks'
    | '/finance/budgets'
    | '/finance/cost-centers'
    | '/finance/dashboard'
    | '/finance/discounts'
    | '/finance/expenses'
    | '/finance/fees'
    | '/finance/ledger'
    | '/finance/payments'
    | '/finance/reports'
    | '/finance/students'
    | '/finance/treasury'
    | '/finance/trial-balance'
    | '/finance/vendors'
    | '/guardians/$id'
    | '/hr/attendance'
    | '/hr/contracts'
    | '/hr/dashboard'
    | '/hr/evaluations'
    | '/hr/leaves'
    | '/hr/org-chart'
    | '/hr/payroll'
    | '/hr/reports'
    | '/inventory/items'
    | '/library/distribution'
    | '/library/textbooks'
    | '/settings/trash'
    | '/students/$id'
    | '/students/new'
    | '/teachers/$id'
    | '/transport/routes'
    | '/transport/students'
    | '/exams'
    | '/finance'
    | '/guardians'
    | '/students'
    | '/teachers'
    | '/hr/staff/$id'
    | '/hr/staff'
  id:
    | '__root__'
    | '/'
    | '/academic'
    | '/admin'
    | '/attendance'
    | '/clinic'
    | '/discipline'
    | '/exams'
    | '/facilities'
    | '/finance'
    | '/guardians'
    | '/hr'
    | '/inventory'
    | '/library'
    | '/profile'
    | '/schedule'
    | '/settings'
    | '/students'
    | '/teachers'
    | '/transport'
    | '/academic/assignments'
    | '/academic/classes'
    | '/academic/subjects'
    | '/academic/years'
    | '/admin/activity-log'
    | '/admin/backup'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/users'
    | '/admissions/$id'
    | '/attendance/reports'
    | '/attendance/take'
    | '/clinic/visits'
    | '/discipline/incidents'
    | '/discipline/merits'
    | '/exams/grades'
    | '/exams/reports'
    | '/facilities/dashboard'
    | '/facilities/maintenance'
    | '/facilities/rooms'
    | '/finance/accounts'
    | '/finance/advanced'
    | '/finance/banks'
    | '/finance/budgets'
    | '/finance/cost-centers'
    | '/finance/dashboard'
    | '/finance/discounts'
    | '/finance/expenses'
    | '/finance/fees'
    | '/finance/ledger'
    | '/finance/payments'
    | '/finance/reports'
    | '/finance/students'
    | '/finance/treasury'
    | '/finance/trial-balance'
    | '/finance/vendors'
    | '/guardians/$id'
    | '/hr/attendance'
    | '/hr/contracts'
    | '/hr/dashboard'
    | '/hr/evaluations'
    | '/hr/leaves'
    | '/hr/org-chart'
    | '/hr/payroll'
    | '/hr/reports'
    | '/inventory/items'
    | '/library/distribution'
    | '/library/textbooks'
    | '/settings/trash'
    | '/students/$id'
    | '/students/new'
    | '/teachers/$id'
    | '/transport/routes'
    | '/transport/students'
    | '/exams/'
    | '/finance/'
    | '/guardians/'
    | '/students/'
    | '/teachers/'
    | '/hr/staff/$id'
    | '/hr/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicRoute: typeof AcademicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AttendanceRoute: typeof AttendanceRouteWithChildren
  ClinicRoute: typeof ClinicRouteWithChildren
  DisciplineRoute: typeof DisciplineRouteWithChildren
  ExamsRoute: typeof ExamsRouteWithChildren
  FacilitiesRoute: typeof FacilitiesRouteWithChildren
  FinanceRoute: typeof FinanceRouteWithChildren
  GuardiansRoute: typeof GuardiansRouteWithChildren
  HrRoute: typeof HrRouteWithChildren
  InventoryRoute: typeof InventoryRouteWithChildren
  LibraryRoute: typeof LibraryRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StudentsRoute: typeof StudentsRouteWithChildren
  TeachersRoute: typeof TeachersRouteWithChildren
  TransportRoute: typeof TransportRouteWithChildren
  AdmissionsIdRoute: typeof AdmissionsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardians': {
      id: '/guardians'
      path: '/guardians'
      fullPath: '/guardians'
      preLoaderRoute: typeof GuardiansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discipline': {
      id: '/discipline'
      path: '/discipline'
      fullPath: '/discipline'
      preLoaderRoute: typeof DisciplineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic': {
      id: '/clinic'
      path: '/clinic'
      fullPath: '/clinic'
      preLoaderRoute: typeof ClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic': {
      id: '/academic'
      path: '/academic'
      fullPath: '/academic'
      preLoaderRoute: typeof AcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/'
      fullPath: '/teachers/'
      preLoaderRoute: typeof TeachersIndexRouteImport
      parentRoute: typeof TeachersRoute
    }
    '/students/': {
      id: '/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/guardians/': {
      id: '/guardians/'
      path: '/'
      fullPath: '/guardians/'
      preLoaderRoute: typeof GuardiansIndexRouteImport
      parentRoute: typeof GuardiansRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/exams/': {
      id: '/exams/'
      path: '/'
      fullPath: '/exams/'
      preLoaderRoute: typeof ExamsIndexRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/transport/students': {
      id: '/transport/students'
      path: '/students'
      fullPath: '/transport/students'
      preLoaderRoute: typeof TransportStudentsRouteImport
      parentRoute: typeof TransportRoute
    }
    '/transport/routes': {
      id: '/transport/routes'
      path: '/routes'
      fullPath: '/transport/routes'
      preLoaderRoute: typeof TransportRoutesRouteImport
      parentRoute: typeof TransportRoute
    }
    '/teachers/$id': {
      id: '/teachers/$id'
      path: '/$id'
      fullPath: '/teachers/$id'
      preLoaderRoute: typeof TeachersIdRouteImport
      parentRoute: typeof TeachersRoute
    }
    '/students/new': {
      id: '/students/new'
      path: '/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof StudentsNewRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/settings/trash': {
      id: '/settings/trash'
      path: '/trash'
      fullPath: '/settings/trash'
      preLoaderRoute: typeof SettingsTrashRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/library/textbooks': {
      id: '/library/textbooks'
      path: '/textbooks'
      fullPath: '/library/textbooks'
      preLoaderRoute: typeof LibraryTextbooksRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/distribution': {
      id: '/library/distribution'
      path: '/distribution'
      fullPath: '/library/distribution'
      preLoaderRoute: typeof LibraryDistributionRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/inventory/items': {
      id: '/inventory/items'
      path: '/items'
      fullPath: '/inventory/items'
      preLoaderRoute: typeof InventoryItemsRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/hr/reports': {
      id: '/hr/reports'
      path: '/reports'
      fullPath: '/hr/reports'
      preLoaderRoute: typeof HrReportsRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/payroll': {
      id: '/hr/payroll'
      path: '/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof HrPayrollRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/org-chart': {
      id: '/hr/org-chart'
      path: '/org-chart'
      fullPath: '/hr/org-chart'
      preLoaderRoute: typeof HrOrgChartRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/leaves': {
      id: '/hr/leaves'
      path: '/leaves'
      fullPath: '/hr/leaves'
      preLoaderRoute: typeof HrLeavesRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/evaluations': {
      id: '/hr/evaluations'
      path: '/evaluations'
      fullPath: '/hr/evaluations'
      preLoaderRoute: typeof HrEvaluationsRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/dashboard': {
      id: '/hr/dashboard'
      path: '/dashboard'
      fullPath: '/hr/dashboard'
      preLoaderRoute: typeof HrDashboardRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/contracts': {
      id: '/hr/contracts'
      path: '/contracts'
      fullPath: '/hr/contracts'
      preLoaderRoute: typeof HrContractsRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/attendance': {
      id: '/hr/attendance'
      path: '/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof HrAttendanceRouteImport
      parentRoute: typeof HrRoute
    }
    '/guardians/$id': {
      id: '/guardians/$id'
      path: '/$id'
      fullPath: '/guardians/$id'
      preLoaderRoute: typeof GuardiansIdRouteImport
      parentRoute: typeof GuardiansRoute
    }
    '/finance/vendors': {
      id: '/finance/vendors'
      path: '/vendors'
      fullPath: '/finance/vendors'
      preLoaderRoute: typeof FinanceVendorsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/trial-balance': {
      id: '/finance/trial-balance'
      path: '/trial-balance'
      fullPath: '/finance/trial-balance'
      preLoaderRoute: typeof FinanceTrialBalanceRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/treasury': {
      id: '/finance/treasury'
      path: '/treasury'
      fullPath: '/finance/treasury'
      preLoaderRoute: typeof FinanceTreasuryRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/students': {
      id: '/finance/students'
      path: '/students'
      fullPath: '/finance/students'
      preLoaderRoute: typeof FinanceStudentsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/reports': {
      id: '/finance/reports'
      path: '/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof FinanceReportsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/payments': {
      id: '/finance/payments'
      path: '/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof FinancePaymentsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/ledger': {
      id: '/finance/ledger'
      path: '/ledger'
      fullPath: '/finance/ledger'
      preLoaderRoute: typeof FinanceLedgerRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/fees': {
      id: '/finance/fees'
      path: '/fees'
      fullPath: '/finance/fees'
      preLoaderRoute: typeof FinanceFeesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/expenses': {
      id: '/finance/expenses'
      path: '/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof FinanceExpensesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/discounts': {
      id: '/finance/discounts'
      path: '/discounts'
      fullPath: '/finance/discounts'
      preLoaderRoute: typeof FinanceDiscountsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/dashboard': {
      id: '/finance/dashboard'
      path: '/dashboard'
      fullPath: '/finance/dashboard'
      preLoaderRoute: typeof FinanceDashboardRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/cost-centers': {
      id: '/finance/cost-centers'
      path: '/cost-centers'
      fullPath: '/finance/cost-centers'
      preLoaderRoute: typeof FinanceCostCentersRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/budgets': {
      id: '/finance/budgets'
      path: '/budgets'
      fullPath: '/finance/budgets'
      preLoaderRoute: typeof FinanceBudgetsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/banks': {
      id: '/finance/banks'
      path: '/banks'
      fullPath: '/finance/banks'
      preLoaderRoute: typeof FinanceBanksRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/advanced': {
      id: '/finance/advanced'
      path: '/advanced'
      fullPath: '/finance/advanced'
      preLoaderRoute: typeof FinanceAdvancedRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/accounts': {
      id: '/finance/accounts'
      path: '/accounts'
      fullPath: '/finance/accounts'
      preLoaderRoute: typeof FinanceAccountsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/facilities/rooms': {
      id: '/facilities/rooms'
      path: '/rooms'
      fullPath: '/facilities/rooms'
      preLoaderRoute: typeof FacilitiesRoomsRouteImport
      parentRoute: typeof FacilitiesRoute
    }
    '/facilities/maintenance': {
      id: '/facilities/maintenance'
      path: '/maintenance'
      fullPath: '/facilities/maintenance'
      preLoaderRoute: typeof FacilitiesMaintenanceRouteImport
      parentRoute: typeof FacilitiesRoute
    }
    '/facilities/dashboard': {
      id: '/facilities/dashboard'
      path: '/dashboard'
      fullPath: '/facilities/dashboard'
      preLoaderRoute: typeof FacilitiesDashboardRouteImport
      parentRoute: typeof FacilitiesRoute
    }
    '/exams/reports': {
      id: '/exams/reports'
      path: '/reports'
      fullPath: '/exams/reports'
      preLoaderRoute: typeof ExamsReportsRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/exams/grades': {
      id: '/exams/grades'
      path: '/grades'
      fullPath: '/exams/grades'
      preLoaderRoute: typeof ExamsGradesRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/discipline/merits': {
      id: '/discipline/merits'
      path: '/merits'
      fullPath: '/discipline/merits'
      preLoaderRoute: typeof DisciplineMeritsRouteImport
      parentRoute: typeof DisciplineRoute
    }
    '/discipline/incidents': {
      id: '/discipline/incidents'
      path: '/incidents'
      fullPath: '/discipline/incidents'
      preLoaderRoute: typeof DisciplineIncidentsRouteImport
      parentRoute: typeof DisciplineRoute
    }
    '/clinic/visits': {
      id: '/clinic/visits'
      path: '/visits'
      fullPath: '/clinic/visits'
      preLoaderRoute: typeof ClinicVisitsRouteImport
      parentRoute: typeof ClinicRoute
    }
    '/attendance/take': {
      id: '/attendance/take'
      path: '/take'
      fullPath: '/attendance/take'
      preLoaderRoute: typeof AttendanceTakeRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/attendance/reports': {
      id: '/attendance/reports'
      path: '/reports'
      fullPath: '/attendance/reports'
      preLoaderRoute: typeof AttendanceReportsRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/admissions/$id': {
      id: '/admissions/$id'
      path: '/admissions/$id'
      fullPath: '/admissions/$id'
      preLoaderRoute: typeof AdmissionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backup': {
      id: '/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AdminBackupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity-log': {
      id: '/admin/activity-log'
      path: '/activity-log'
      fullPath: '/admin/activity-log'
      preLoaderRoute: typeof AdminActivityLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/academic/years': {
      id: '/academic/years'
      path: '/years'
      fullPath: '/academic/years'
      preLoaderRoute: typeof AcademicYearsRouteImport
      parentRoute: typeof AcademicRoute
    }
    '/academic/subjects': {
      id: '/academic/subjects'
      path: '/subjects'
      fullPath: '/academic/subjects'
      preLoaderRoute: typeof AcademicSubjectsRouteImport
      parentRoute: typeof AcademicRoute
    }
    '/academic/classes': {
      id: '/academic/classes'
      path: '/classes'
      fullPath: '/academic/classes'
      preLoaderRoute: typeof AcademicClassesRouteImport
      parentRoute: typeof AcademicRoute
    }
    '/academic/assignments': {
      id: '/academic/assignments'
      path: '/assignments'
      fullPath: '/academic/assignments'
      preLoaderRoute: typeof AcademicAssignmentsRouteImport
      parentRoute: typeof AcademicRoute
    }
    '/hr/staff/': {
      id: '/hr/staff/'
      path: '/staff'
      fullPath: '/hr/staff/'
      preLoaderRoute: typeof HrStaffIndexRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/staff/$id': {
      id: '/hr/staff/$id'
      path: '/staff/$id'
      fullPath: '/hr/staff/$id'
      preLoaderRoute: typeof HrStaffIdRouteImport
      parentRoute: typeof HrRoute
    }
  }
}

interface AcademicRouteChildren {
  AcademicAssignmentsRoute: typeof AcademicAssignmentsRoute
  AcademicClassesRoute: typeof AcademicClassesRoute
  AcademicSubjectsRoute: typeof AcademicSubjectsRoute
  AcademicYearsRoute: typeof AcademicYearsRoute
}

const AcademicRouteChildren: AcademicRouteChildren = {
  AcademicAssignmentsRoute: AcademicAssignmentsRoute,
  AcademicClassesRoute: AcademicClassesRoute,
  AcademicSubjectsRoute: AcademicSubjectsRoute,
  AcademicYearsRoute: AcademicYearsRoute,
}

const AcademicRouteWithChildren = AcademicRoute._addFileChildren(
  AcademicRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityLogRoute: typeof AdminActivityLogRoute
  AdminBackupRoute: typeof AdminBackupRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityLogRoute: AdminActivityLogRoute,
  AdminBackupRoute: AdminBackupRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AttendanceRouteChildren {
  AttendanceReportsRoute: typeof AttendanceReportsRoute
  AttendanceTakeRoute: typeof AttendanceTakeRoute
}

const AttendanceRouteChildren: AttendanceRouteChildren = {
  AttendanceReportsRoute: AttendanceReportsRoute,
  AttendanceTakeRoute: AttendanceTakeRoute,
}

const AttendanceRouteWithChildren = AttendanceRoute._addFileChildren(
  AttendanceRouteChildren,
)

interface ClinicRouteChildren {
  ClinicVisitsRoute: typeof ClinicVisitsRoute
}

const ClinicRouteChildren: ClinicRouteChildren = {
  ClinicVisitsRoute: ClinicVisitsRoute,
}

const ClinicRouteWithChildren =
  ClinicRoute._addFileChildren(ClinicRouteChildren)

interface DisciplineRouteChildren {
  DisciplineIncidentsRoute: typeof DisciplineIncidentsRoute
  DisciplineMeritsRoute: typeof DisciplineMeritsRoute
}

const DisciplineRouteChildren: DisciplineRouteChildren = {
  DisciplineIncidentsRoute: DisciplineIncidentsRoute,
  DisciplineMeritsRoute: DisciplineMeritsRoute,
}

const DisciplineRouteWithChildren = DisciplineRoute._addFileChildren(
  DisciplineRouteChildren,
)

interface ExamsRouteChildren {
  ExamsGradesRoute: typeof ExamsGradesRoute
  ExamsReportsRoute: typeof ExamsReportsRoute
  ExamsIndexRoute: typeof ExamsIndexRoute
}

const ExamsRouteChildren: ExamsRouteChildren = {
  ExamsGradesRoute: ExamsGradesRoute,
  ExamsReportsRoute: ExamsReportsRoute,
  ExamsIndexRoute: ExamsIndexRoute,
}

const ExamsRouteWithChildren = ExamsRoute._addFileChildren(ExamsRouteChildren)

interface FacilitiesRouteChildren {
  FacilitiesDashboardRoute: typeof FacilitiesDashboardRoute
  FacilitiesMaintenanceRoute: typeof FacilitiesMaintenanceRoute
  FacilitiesRoomsRoute: typeof FacilitiesRoomsRoute
}

const FacilitiesRouteChildren: FacilitiesRouteChildren = {
  FacilitiesDashboardRoute: FacilitiesDashboardRoute,
  FacilitiesMaintenanceRoute: FacilitiesMaintenanceRoute,
  FacilitiesRoomsRoute: FacilitiesRoomsRoute,
}

const FacilitiesRouteWithChildren = FacilitiesRoute._addFileChildren(
  FacilitiesRouteChildren,
)

interface FinanceRouteChildren {
  FinanceAccountsRoute: typeof FinanceAccountsRoute
  FinanceAdvancedRoute: typeof FinanceAdvancedRoute
  FinanceBanksRoute: typeof FinanceBanksRoute
  FinanceBudgetsRoute: typeof FinanceBudgetsRoute
  FinanceCostCentersRoute: typeof FinanceCostCentersRoute
  FinanceDashboardRoute: typeof FinanceDashboardRoute
  FinanceDiscountsRoute: typeof FinanceDiscountsRoute
  FinanceExpensesRoute: typeof FinanceExpensesRoute
  FinanceFeesRoute: typeof FinanceFeesRoute
  FinanceLedgerRoute: typeof FinanceLedgerRoute
  FinancePaymentsRoute: typeof FinancePaymentsRoute
  FinanceReportsRoute: typeof FinanceReportsRoute
  FinanceStudentsRoute: typeof FinanceStudentsRoute
  FinanceTreasuryRoute: typeof FinanceTreasuryRoute
  FinanceTrialBalanceRoute: typeof FinanceTrialBalanceRoute
  FinanceVendorsRoute: typeof FinanceVendorsRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceAccountsRoute: FinanceAccountsRoute,
  FinanceAdvancedRoute: FinanceAdvancedRoute,
  FinanceBanksRoute: FinanceBanksRoute,
  FinanceBudgetsRoute: FinanceBudgetsRoute,
  FinanceCostCentersRoute: FinanceCostCentersRoute,
  FinanceDashboardRoute: FinanceDashboardRoute,
  FinanceDiscountsRoute: FinanceDiscountsRoute,
  FinanceExpensesRoute: FinanceExpensesRoute,
  FinanceFeesRoute: FinanceFeesRoute,
  FinanceLedgerRoute: FinanceLedgerRoute,
  FinancePaymentsRoute: FinancePaymentsRoute,
  FinanceReportsRoute: FinanceReportsRoute,
  FinanceStudentsRoute: FinanceStudentsRoute,
  FinanceTreasuryRoute: FinanceTreasuryRoute,
  FinanceTrialBalanceRoute: FinanceTrialBalanceRoute,
  FinanceVendorsRoute: FinanceVendorsRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface GuardiansRouteChildren {
  GuardiansIdRoute: typeof GuardiansIdRoute
  GuardiansIndexRoute: typeof GuardiansIndexRoute
}

const GuardiansRouteChildren: GuardiansRouteChildren = {
  GuardiansIdRoute: GuardiansIdRoute,
  GuardiansIndexRoute: GuardiansIndexRoute,
}

const GuardiansRouteWithChildren = GuardiansRoute._addFileChildren(
  GuardiansRouteChildren,
)

interface HrRouteChildren {
  HrAttendanceRoute: typeof HrAttendanceRoute
  HrContractsRoute: typeof HrContractsRoute
  HrDashboardRoute: typeof HrDashboardRoute
  HrEvaluationsRoute: typeof HrEvaluationsRoute
  HrLeavesRoute: typeof HrLeavesRoute
  HrOrgChartRoute: typeof HrOrgChartRoute
  HrPayrollRoute: typeof HrPayrollRoute
  HrReportsRoute: typeof HrReportsRoute
  HrStaffIdRoute: typeof HrStaffIdRoute
  HrStaffIndexRoute: typeof HrStaffIndexRoute
}

const HrRouteChildren: HrRouteChildren = {
  HrAttendanceRoute: HrAttendanceRoute,
  HrContractsRoute: HrContractsRoute,
  HrDashboardRoute: HrDashboardRoute,
  HrEvaluationsRoute: HrEvaluationsRoute,
  HrLeavesRoute: HrLeavesRoute,
  HrOrgChartRoute: HrOrgChartRoute,
  HrPayrollRoute: HrPayrollRoute,
  HrReportsRoute: HrReportsRoute,
  HrStaffIdRoute: HrStaffIdRoute,
  HrStaffIndexRoute: HrStaffIndexRoute,
}

const HrRouteWithChildren = HrRoute._addFileChildren(HrRouteChildren)

interface InventoryRouteChildren {
  InventoryItemsRoute: typeof InventoryItemsRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryItemsRoute: InventoryItemsRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

interface LibraryRouteChildren {
  LibraryDistributionRoute: typeof LibraryDistributionRoute
  LibraryTextbooksRoute: typeof LibraryTextbooksRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryDistributionRoute: LibraryDistributionRoute,
  LibraryTextbooksRoute: LibraryTextbooksRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

interface SettingsRouteChildren {
  SettingsTrashRoute: typeof SettingsTrashRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsTrashRoute: SettingsTrashRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface StudentsRouteChildren {
  StudentsIdRoute: typeof StudentsIdRoute
  StudentsNewRoute: typeof StudentsNewRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsIdRoute: StudentsIdRoute,
  StudentsNewRoute: StudentsNewRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

interface TeachersRouteChildren {
  TeachersIdRoute: typeof TeachersIdRoute
  TeachersIndexRoute: typeof TeachersIndexRoute
}

const TeachersRouteChildren: TeachersRouteChildren = {
  TeachersIdRoute: TeachersIdRoute,
  TeachersIndexRoute: TeachersIndexRoute,
}

const TeachersRouteWithChildren = TeachersRoute._addFileChildren(
  TeachersRouteChildren,
)

interface TransportRouteChildren {
  TransportRoutesRoute: typeof TransportRoutesRoute
  TransportStudentsRoute: typeof TransportStudentsRoute
}

const TransportRouteChildren: TransportRouteChildren = {
  TransportRoutesRoute: TransportRoutesRoute,
  TransportStudentsRoute: TransportStudentsRoute,
}

const TransportRouteWithChildren = TransportRoute._addFileChildren(
  TransportRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicRoute: AcademicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AttendanceRoute: AttendanceRouteWithChildren,
  ClinicRoute: ClinicRouteWithChildren,
  DisciplineRoute: DisciplineRouteWithChildren,
  ExamsRoute: ExamsRouteWithChildren,
  FacilitiesRoute: FacilitiesRouteWithChildren,
  FinanceRoute: FinanceRouteWithChildren,
  GuardiansRoute: GuardiansRouteWithChildren,
  HrRoute: HrRouteWithChildren,
  InventoryRoute: InventoryRouteWithChildren,
  LibraryRoute: LibraryRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StudentsRoute: StudentsRouteWithChildren,
  TeachersRoute: TeachersRouteWithChildren,
  TransportRoute: TransportRouteWithChildren,
  AdmissionsIdRoute: AdmissionsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
